### ISSUE TITLE
Please, include CVE-2017-1000117 fix

### ISSUE THREAD

**Issue by yuriy-chumak** [git/git-scm.com#1016]
Fix for critical CVE-2017-1000117 included into [Git 2.7.6-2.14.1](https://lkml.org/lkml/2017/8/10/757). Please, update the code base and installation packages.

> A malicious third-party can give a crafted "ssh://..." URL to an
unsuspecting victim, and an attempt to visit the URL can result in
any program that exists on the victim's machine being executed.
Such a URL could be placed in the .gitmodules file of a malicious
project, and an unsuspecting victim could be tricked into running
"git clone --recurse-submodules" to trigger the vulnerability.

**Comment by peff** [comment]
This issue tracker is just for the website content itself. The fix is already in released versions of Git, and the site auto-updates as new versions become available (the front page should already link to 2.14.1). Some binary packages (like the OS X one) tend to lag, but there's nothing we can do here. You have to nag the packagers (and then we'll pick up new releases automatically).
