### ISSUE TITLE
Improve version listing on git docs pages

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1048]
Since #1045 was merged, manual pages (under /docs) may display an huge number of versions for a git command.

The best (worst?) example may be https://git-scm.com/docs/git

![photos_ - 1](https://user-images.githubusercontent.com/1999050/31462190-bb84a5f0-aec3-11e7-8685-9217a620f9bc.jpg)

The frontend should prevent this kind of problems (by using scroll for instance)

**Comment by jnavila** [comment]
I still don't grab why the site should propose documentation for completely outdated versions of the commands. So, the proposition would be to only list up to a certain number of previous versions. It may not fit with the versions available in LTS distribs, but who cares what commands look like in pre 1.0 versions of Git?

**Comment by pedrorijo91** [comment]
I agree we shoudln't need to list all the versions. But you can't just select the last X versions. Probably (and unfortunately) it's still relevant to show git 1.9.x docs because of Ubuntu an other OS that come with such versions by default

**Comment by peff** [comment]
Yes, this was already pretty bad before #1045 (where we'd go back to v2.0 or so), but is even worse now. Having a cutoff on the server side would also help with the CPU-time problems of #1045, but it's actually a little tricky to do. The original limit applied at the outset meant we only walked back a certain number of tags, even though there may not have been changes there. So `git cherry`, for example, ends up with no changes. But maybe that's fine, if it hasn't been touched in any recent version of Git.

On the other hand, it's nice if we can make all the data available so that somebody with an antique version of Git really can click-through to see the full list if they want to. And that argues for just making the lower part of the list invisible, with a javascript `more` button to make it visible.

Probably whatever ships with Debian stable, Ubuntu LTS, or RHEL is a reasonable cutoff. I suspect we could also just omit point releases as we go far back to reduce the size of the list. OTOH, if nothing changed in the point releases then they'd already be collapsed down in the current view.

Or I guess we could just say "show 10 entries, and everything else is hidden behind a button".

I'd really be OK with any of those. Whoever puts the work into implementing is free to decide.

**Comment by jasonlong** [comment]
FWIW, the new design I'm working on has a `max-height` for this dropdown container with the contents being scrollable.

![dropdown](https://user-images.githubusercontent.com/6104/36991728-960edb18-2076-11e8-9ba4-dbd0315f7213.gif)

**Comment by jasonlong** [comment]
Closing this as it's being addressed in #1162.
