### ISSUE TITLE
Delete unnecessary old branches

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1051]
There are a few old branches (https://github.com/git/git-scm.com/branches/all) in this repository. Besides the contributors-page branch, the other seem to be old work that we don't want to keep or that's so outdated that the changes would need to be reviewed completely.

@peff @jnavila @sxlijin what do you think? just a minor cleaning :)

**Comment by peff** [comment]
Anything that's been merged should obviously be deleted.

Anything with a closed PR should probably be deleted. GitHub holds onto the tips via `refs/pull`, so it can always be restored if necessary. A few of the branches in this state could not be deleted because "they have open pull requests". But this can be tricky if the PR is spammy, since it doesn't appear in the PR list, then. For contributors-page, I closed #385 (which I found via `git for-each-ref --contains`). But I can't seem to find any PR that refers to the `github` branch. I think I'll just delete it manually via Git.

For anything else, deleting the branch would lose any reference to the work in question. So it may be worth pinging the author before deleting.

**Comment by pedrorijo91** [comment]
There's only 1 branch remaining: git-for-windows, which tries to [introduce a new git for windows page](https://github.com/git/git-scm.com/commit/8be14101aa598f88f7a442cfe80503d0075c082c)

Can you tell us if this work should be kept or deleted @blackant ?

**Comment by jasonlong** [comment]
Thanks @pedrorijo91, that can be deleted. (@blackant used to be my username 😺 )
