### ISSUE TITLE
Error: Could not fork child process: Resource temporarily unavailable (-1). 

### ISSUE THREAD

**Issue by theprogrammingthinker** [git/git-scm.com#1081]
Error: Could not fork child process: Resource temporarily unavailable (-1).
DLL rebasing may be required; see 'rebaseall / rebase --help'.
![capture](https://user-images.githubusercontent.com/15184185/33160629-19c50b0a-d048-11e7-867b-012c2a7803f5.PNG)

**Comment by pedrorijo91** [comment]
Hey @theprogrammingthinker,

As you can see in the issue template (https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository is not the proper way to report issues about git itself. You should follow the steps at https://git-scm.com/community to report your problem.

Also, this issue does not contain enough information to be debugged. Make sure you include what you are trying to achieve, the steps you are following, and the expected output.

**Comment by jnavila** [comment]
@pedrorijo91 So much for the additional warning :stuck_out_tongue:

**Comment by pedrorijo91** [comment]
@jnavila  true :( I think we need to develop a captcha v3 for this 😅

**Comment by theprogrammingthinker** [comment]
@pedrorijo91 sorry for that. anyway, thank you.

**Comment by jnavila** [comment]
@theprogrammingthinker No problem. You're facing an issue and looking for help; that's sane.

**Comment by gamitech** [comment]
Here is the fix.
1 Go to you Windows Defender Security Center settings
2 Click on App & Browser Control
3 At the bottom click on the "Exploit Protection Settings" link
4 Go to "Program Settings" and click on the "Add program to customize" -> "Choose exact file path"
5 Navigate to "C:\Program Files\Git\usr\bin\sh.exe" and add it
6 Override and turn off the following:
Mandatory ASLR
Randomize memory allocations (Bottom-up ASLR)
7 Click "Apply" and now everything should work fine.

Good luck,
Gabriel

**Comment by sxlijin** [comment]
NO NO NO NO NO NO NO NO NO NO NO NO NO. 

**Turning off ASLR is not OK.** This is a seriously important kernel-level security measure. Do not advise people to turn it off.

**Comment by gamitech** [comment]
Please read my comment before going NO NO NO.
I said they need to be disabled for those **_executables only_**. They cannot work and are not compatible with these features (high randomization , high entropy ASLR) becasue they "assume" the load address of some DLLs which ASLR pretty much wants you to not assume. Turning it off only for those processes until the problem is fixed will not cause any harm as before the the ASLR was turned off for them by default. I work in this field trust me, those processes were broken before this versio of Windows 10. This one just made a feature default which was not there before by default.
Anyway, ignoring what @sxlijin is saying, if you want them to work just they way they did before, no more no less secure, you simply need to turn those features off. The rest of the OS will work in its default mode for existing processes and files.
You will also notice if you look in the Program Settings that Microsoft themselves disable some if these feature for some of their executable or other incompatible ( crappy ) software.
Cheers, all.

**Comment by sxlijin** [comment]
@gamitech: apologies for the tone of my initial response, but please remember that GitHub is a public forum, and people often come in from search results when trying to find a fix for whatever issue they have. Simply recommending that people turn off ASLR for whatever binary is borking itself is *not* a good recipe for secure systems.

Now that you've *explained* why the fix is both acceptable and necessary, I have no issue with your recommendation. Also, if anyone watching this knows what issue in git-for-windows/git should be cross-linked, please link it - I couldn't find it after a cursory search.

**Comment by sxlijin** [comment]
Nvm. Found it - git-for-windows/git#1412.

**Comment by gamitech** [comment]
@sxlijin  No problem man! ;)

**Comment by avenue19** [comment]
Tried gamitech's suggestion and it had no effect for me. I uninstalled 2.17 and installed 2.18, and that fixed it.

**Comment by acinnes** [comment]
I was tripped up by this today, in connection with WSL Terminal and Git Bash. Disabling ASLR for relevant binaries does fix it, but the list of binaries is unclear and potentially long. See https://github.com/mintty/wsltty/issues/6#issuecomment-415961012 for instructions on scripting the ASLR disable step for all binaries under a base directory.

**Comment by amosbatista** [comment]
Hi. I was with this problem, but I could get throught it disabling my antivirus.

**Comment by lopandpe** [comment]
Resolution for me, 3 years before:

https://github.com/mintty/wsltty/issues/6#issuecomment-419589599

**Comment by G00Dway** [comment]
> Here is the fix. 1 Go to you Windows Defender Security Center settings 2 Click on App & Browser Control 3 At the bottom click on the "Exploit Protection Settings" link 4 Go to "Program Settings" and click on the "Add program to customize" -> "Choose exact file path" 5 Navigate to "C:\Program Files\Git\usr\bin\sh.exe" and add it 6 Override and turn off the following: Mandatory ASLR Randomize memory allocations (Bottom-up ASLR) 7 Click "Apply" and now everything should work fine.
> 
> Good luck, Gabriel

didnt work :(

**Comment by Fabian-Hillary** [comment]
Here is the fix. 1 Go to you Windows Defender Security Center settings 2 Click on App & Browser Control 3 At the bottom click on the "Exploit Protection Settings" link 4 Go to "Program Settings" and click on the "Add program to customize" -> "Choose exact file path" 5 Navigate to "C:\Program Files\Git\usr\bin\sh.exe" and add it 6 Override and turn off the following: Mandatory ASLR Randomize memory allocations (Bottom-up ASLR) 7 Click "Apply" and now everything should work fine.

Good luck, Gabriel THIS DID NOT WORK

**Comment by Ritesh1707** [comment]
Didn't work on my device alany other suggestions

**Comment by Johnyboy234** [comment]
| Header | Header |
|--------|--------|
| Cell | Cell |
| Cell | Cell |

**Comment by antgustech** [comment]
What do you if you machine is work issued and only admin can change defender settings?
