### ISSUE TITLE
Weird behavior when downloading Git for Windows

### ISSUE THREAD

**Issue by Dibro89** [git/git-scm.com#1129]
I'm using latest Google Chrome 64.0.3282.119 on **64-bit** Windows 10 Pro.

When I try to download Git using
https://git-scm.com/download/win/
it suggests me the correct 64-bit version.

But when I use this link
https://git-scm.com/download/win _<- notice: no slash_
it suggests me 32-bit version.

According to `/app/controllers/downloads_controller.rb` version is extracted from `HTTP_USER_AGENT`,
but `user-agent` my browser sends is the same in both cases.

**Comment by pedrorijo91** [comment]
Hey @Dibro89, thanks for reporting the issue!

It seems to be possible to reproduce the error using other SO (mac OS X on my case). I'll try to have a better look at this still today

**Comment by pedrorijo91** [comment]
running the website locally I can't reproduce the problem, despite the fact I can reproduce it in the live website. 

I saw that the live website is using unicorn and locally I was using WEBrick. I've tried to run unicorn locally (`bundle exec unicorn -c ./config/unicorn.rb`) but still can't reproduce

Are you aware of anything special we have on heroku that might affect this @peff ?

**Comment by Dibro89** [comment]
@pedrorijo91 it works as intended, both links suggest me 64-bit version.

**Comment by Dibro89** [comment]
@pedrorijo91 I think this can be easily fixed by detecting "bitness" on the client side using JavaScript,
see: https://stackoverflow.com/questions/1741933, I can make a PR, if you don't mind.

**Comment by peff** [comment]
Thanks for digging out the root cause. I think it's great if we can remove as much of this server-side logic as possible (one, because it's obviously broken by the aggressive caching config; but two, I still have hopes that one day this could be converted to a static site).

You should be able to reproduce the same user-agent logic in javascript. We also include [session.js](https://github.com/codejoust/session.js) already, which has some similar logic and could possibly be helpful (though it looks like it only gives OS, not architecture, so maybe not).

**Comment by Dibro89** [comment]
@peff @pedrorijo91 Please, take a look at the commit and check if all variables are properly interpolated.

**Comment by pedrorijo91** [comment]
I think in the overall the downloads section is just wrong:

* the mac download page doesn't start the download automatically 
* the linux download page lists a set of commands
* the windows download page downloads automatically, detecting the 'bitness'

we have 3 different user experiences.

Let's see how others deal with this problem:

1. Google chrome
* Download page at https://www.google.com/chrome/
* Button to start download on detected platform
* hint below the button to tell what version it will download
* link to download to other platforms
* next page at https://www.google.com/chrome/browser/thankyou.html?statcb=1 that automatically downloads for detected platform

2. Firefox
* Download page (actually, it's in the homepage) at https://www.mozilla.org/en-US/firefox/new/ 
* Button to start download on detect platform (no hint this time)
* Next page at https://www.mozilla.org/en-US/firefox/new/?scene=2 with link to download to other platforms
* Next page will download automatically detected platform

3. Dropbox
* Download page at https://www.dropbox.com/install
* Button to download for detected platform (no hint, no link to automatically download, no way to download other platforms)

4. Intellij IDEA
* Download page at https://www.jetbrains.com/idea/download
* Download page focus on detected platform but keeps other platforms easily acessible
* Button to download chosen platform

From these, I would prefer to have something like Google Chrome or Intellij IDEA (Dropbox is really hard to download for other platforms, and Firefox misses the hint about which platform was detected)

maybe @jasonlong has some nice thoughts on this since he is the only designer around? :)
(github desktop also seems to follow a similar logic to Intellij IDEA)

All of this implies a bigger change than expected.

How easy would it be to simply disable caching on /download/win and /download/win/ for now @peff ?

**Comment by peff** [comment]
@pedrorijo91 Thanks for laying out those problems. I agree that it would be nice to unify the design and the code a bit, and that it should be easy to get a download by name rather than auto-detecting. I doubt we'll ever have binary packages for Linux, though.

I put in a page rule to override the aggressive caching for `/download/win`. I think in the long run that we should redesign the page so it can be cached (i.e., use javascript for auto-detection but have the various options clickable as a fallback).

(Somewhat orthogonal is that we should actually return correct cache-control headers from the app to cloudflare, and then we could use "normal" caching rules, and make caching rules at the app level. IIRC, I turned on the "cache everything" rules because there are a bunch of pages that _could_ be cached but don't output the correct headers.

**Comment by pedrorijo91** [comment]
I think this can be closed since is solved despite the effort still being done on #1130 to improve some logic

**Comment by cynthiaspence7827** [comment]
My problem is that it starts downloading Git, but it never finishes. It keeps on saying Network Error, then it says Access Denied.

**Comment by JacquesInnocent** [comment]
Download git faster from here for now. (https://en.softonic.com/download/git/windows/post-download)

**Comment by hassankamrul** [comment]
I am using windows10, and the download speed is very very slow. Although in case of downloading other files, it seems quite fast.  Can you please check why it is happening. Thank you.

**Comment by cynthiaspence7827** [comment]
hey my best guess is that you have slow internet connection... or maybe you
need to scan your computer, empty recycle bin, get rid of anything you
don't need. I'm not an IT person, someone who is would be better for this
question. I'm a software engineer, I do code.

**Comment by cynthiaspence7827** [comment]
I aplologize, I thought this was a guy that won't leave me alone. Please
disregard last email.
Very Respectfully
Cynthia

**Comment by cynthiaspence7827** [comment]
Try restarting your computer

**Comment by TerriTauranga** [comment]
> @pedrorijo91 Thanks for laying out those problems. I agree that it would be nice to unify the design and the code a bit, and that it should be easy to get a download by name rather than auto-detecting. I doubt we'll ever have binary packages for Linux, though.
> 
> I put in a page rule to override the aggressive caching for `/download/win`. I think in the long run that we should redesign the page so it can be cached (i.e., use javascript for auto-detection but have the various options clickable as a fallback).
> 
> (Somewhat orthogonal is that we should actually return correct cache-control headers from the app to cloudflare, and then we could use "normal" caching rules, and make caching rules at the app level. IIRC, I turned on the "cache everything" rules because there are a bunch of pages that _could_ be cached but don't output the correct headers.

**Comment by arch-angel7** [comment]
> @pedrorijo91 Thanks for laying out those problems. I agree that it would be nice to unify the design and the code a bit, and that it should be easy to get a download by name rather than auto-detecting. I doubt we'll ever have binary packages for Linux, though.
> 
> I put in a page rule to override the aggressive caching for `/download/win`. I think in the long run that we should redesign the page so it can be cached (i.e., use javascript for auto-detection but have the various options clickable as a fallback).
> 
> (Somewhat orthogonal is that we should actually return correct cache-control headers from the app to cloudflare, and then we could use "normal" caching rules, and make caching rules at the app level. IIRC, I turned on the "cache everything" rules because there are a bunch of pages that _could_ be cached but don't output the correct headers.

/databricks_unzip
