### ISSUE TITLE
Review TODO.txt file

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1140]
There's a [TODO.txt](https://github.com/git/git-scm.com/blob/master/TODO.txt) file that needs to be reviewed. Many of the items are probably no longer interesting, and the remaining should be migrated into github issues.

I suspect a few may be good candidates to first time contributors

**Comment by pedrorijo91** [comment]
I'll have a look on this this week (probably Wednesday and Thursday). Let me know if you have any comments on advance @peff @sxlijin @jnavila

**Comment by peff** [comment]
To be honest, we could probably just declare "todo bankruptcy" and wipe the whole list. If a particular issue is mentioned again, then we can make it into an issue. And if not, then it probably wasn't that important in the first place.

**Comment by jnavila** [comment]
As they say: you must do it today, at least tomorrow or never… We've already brought down the "related" feature, so I guess we're not yet on the path of adding more. Talking usability (which I'm not literate at), I think that the priority should be the rework of the navigation map and ensuring the content is up to date rather than adding cross linking and shiny stuff.

**Comment by pedrorijo91** [comment]
@jasonlong there's one topic about `Fullscreen Manpage (or, hide sidebar)`. I'm not sure if it's worthy, but in case you want to consider it on your redesign :)

@jnavila I have the impression you have been more focused on the book than any other of us, so can I ask your opinion on these topics?

 * link for translation sources
 * show that newer content is available for missed slugs (fallback to v1)
 * incremental updates (get hashes of all pages, only update changed ones)
 * errata / commenting?

**Comment by jnavila** [comment]
> * link for translation sources

Definitely wanted. We have often people landing on progit (english) with issues for translations. The source repo are already available in the task for importing the files but they are not available in DB for dynamic building.

> * show that newer content is available for missed slugs (fallback to v1)

How often is the book v1 accessed? Instead of fallback, getting rid of it would be safer. The repo for v1 is already declared deprecated.

> * incremental updates (get hashes of all pages, only update changed ones)

We don't really care unless @peff can tell there is a non negligible cost induced by that additional processing. The update is checked once a day and triggered only when the content changes.

> * errata / commenting?

Not relevant. The book is now updated live. So, it's mostly up to date and getting better with time.

**Comment by pedrorijo91** [comment]
thanks @jnavila ! I would say that it makes sense to create a new issue for `link for translation sources`.

what about removing the book v1, what do we need? why haven't we removed yet?

**Comment by peff** [comment]
No, as far as I know book processing CPU is not currently a big deal.
