### ISSUE TITLE
Proposal for responsive site design refresh

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1143]
Several weeks ago, I began an effort to clean up the Git site's CSS. My hope of having a clean enough starting point to begin making the site more responsive (per #1084). The CSS was a complete mess – the great majority of it my fault – and I realized that even after making the new linter happy and fixing the overly deep nesting, etc., we'd still wouldn't be in a good place for introducing responsive rules.

I decided to take a step back and see how feasible it might be to start fresh with all new CSS. I took a sample documentation page and spiked a new layout with [Tachyons](http://tachyons.io/).

----

**Sample page design**
👉  **https://nugit.now.sh** 👈 

----

### Screenshots

![image](https://user-images.githubusercontent.com/6104/36170657-f462f1e4-10cd-11e8-9003-298c1b77e6fa.png)

![image](https://user-images.githubusercontent.com/6104/36170808-7b3ef528-10ce-11e8-81c5-20dcf1ed70ce.png)

My original intention wasn't to do a true redesign, but I think a minor refresh is in order after 6 years.

A few updates:

* Responsive (duh).
* Use a more modern system font stack.
* Use SVG icons from [open source Feather project](https://feathericons.com/).
* Move main nav to top.
* Better text contrast.
* SVG logo.

Things to figure out:

* How and if to structure the IA. E.g. I feel like the Book should be a top level section, but we'll learn more once we begin [collecting analytics](https://github.com/git/git-scm.com/pull/1142) again.
* How to handle secondary navigation links. Current thought is to use the collapsing (and expandable on mobile) sidebar like in the page above.
* Perhaps further minimize JS with `<details>` / `<summary>` for expandable sections.
* Probably most importantly, getting some sort of staging site set up that we can deploy to and have the community test out.

If folks are ok with this general direction, I'd like to begin updating the site. Most of the work will be on the front end and a fellow GitHub designer has offered to help out. Minor Rails tweaks may be needed and I have a volunteer for that as well (plus anyone else that wants to lend a hand).

**Comment by JasonEtco** [comment]
This looks awesome @jasonlong 🎉 

For comparison, the current equivalent of the above design: https://git-scm.com/docs/git-shortlog
<details>
<summary>Screenshot of current page</summary>

![image](https://user-images.githubusercontent.com/10660468/36171272-f6219060-10cf-11e8-862f-2cf03aa47deb.png)

</details>

**Comment by pedrorijo91** [comment]
At first sight it seems in the right direction.

One of the major problems was reported on #359, and it is fixed with the new design :)

Just 2 topics:

1. I've seen many articles criticising the burguer menu recently (I don't have any in specific, but google is full of those). But if you feel it's the right choice I'm happy with that.

2. The `<pre>` elements in mobile have an UX problem I hate personally: it's not easy to understand you can (and sometimes you need in order to see everything) scroll horizontally. What are your thoughts? Can we find a better solution?

**Comment by jasonlong** [comment]
> I've seen many articles criticising the burguer menu recently

I feel like the initial backlash has fizzled out and now the metaphor (while not ideal) is so ubiquitous in a mobile context that it's perfectly fine to use.

> The <pre> elements in mobile have an UX problem I hate personally: it's not easy to understand you can (and sometimes you need in order to see everything) scroll horizontally.

Viewing code snippets on a small device isn't an ideal experience no matter what you do. You can choose to wrap long lines, but that breaks a lot of uses where the author was relying on specific whitespace. 

On a more practical note, the `<pre>` tags and the rest of the documentation markup comes from the backend tooling (asciidoc?) and I've never had control over the output. I mean, I'm sure we could request changes, but it's possible to style the existing markup just fine.

**Comment by braian125** [comment]
I want to help with this, it's fantastic!

**Comment by pedrorijo91** [comment]
@jasonlong I agree that reading code snippets on mobile or other similar devices is never going to be great, but just like in the desktop/notebook browser you have the vertical scrollbar always visible, can't we have some horizontal scrollbar present in the snippets? 

while not beautiful (maybe we can find a nice solution), at least the readers would know immediately that they should scroll because some info may be missing.

I know some of the content comes from the asciidoctor (at least the book content, and probably the man pages also?), and if needed maybe we should invest some time looking for important asciidoctor updates or other alternatives (never been through that part of the site, so can't really say if it would be too much work)

Nevertheless this seems an huge improvement, and I am available to help in anything you need of course (reviewing, testing, and coding)

**Comment by jasonlong** [comment]
One thing that would be pretty easy would be to add an `::after` pseudo-element with a `content` attribute of `Drag to scroll` or something on those `<pre>` tags on smaller viewports.

![image](https://user-images.githubusercontent.com/6104/36181672-c6a509ba-10f3-11e8-8502-08171cbd94f4.png)

**Comment by laurendorman** [comment]
This is awesome.

Happy to lend a hand here as I’ve been working with Tachyons for roughly a year now — would love to contribute and share ideas for enhancements, open items, etc.

**Comment by jasonlong** [comment]
@laurendorman Awesome. If you have any feedback on my Tachyon usage thus far, definitely let me know. The repo for this spike is https://github.com/jasonlong/nugit.

**Comment by non-binary** [comment]
This is so pretty. Good work!

**Comment by pedrorijo91** [comment]
@jasonlong I think everyone is with you on this :) How can we help making this happen?

**Comment by jasonlong** [comment]
@pedrorijo91 I've begun working on this in a local branch. I think the most useful thing here will be to get a secondary testing/staging Heroku instance spun up (not sure if their [Flow feature](https://www.heroku.com/flow) makes sense here?) . We'll also need to be careful about making sure updates in `master` find their way into the new branch.

**Comment by pedrorijo91** [comment]
I think only @peff has permissions to setup that

**Comment by peff** [comment]
The heroku app is owned by a team account, so if there's anybody interested in setting up a pipeline with a staging instance, I can add you to the team (@pedrorijo91, I think you're already on the team, but let me know if you run into any permissions problems). It's something I think would be useful to have set up for reviewing all PRs, but I just haven't had time to look into it (and I doubt I will in the near future, either).

**Comment by pedrorijo91** [comment]
I will have a look then. I played with a simpler version of this feature 2 years ago, I supposed it should be as easy to setup as it was. just one thing before doing any action: how does the billing work @peff? Spinning up apps for every PR may affect the monthly bill.

we may also have to do some work to populate the DB when launching a new app (assuming it will launch a new app with a new DB), or having a staging DB that the app should connect to. Will try to have a look on that

**Comment by peff** [comment]
> how does the billing work

We have credits from Heroku that cover the regular billing. I don't know how high those credits would go if we add more services. Any uncovered bill goes to my personal credit card. So please don't add things that cost money. ;)

If we have an idea of what the costs might be, I can talk to the heroku folks about covering it with credits. But I assumed we would be able to spin up free hobby-level dynos for pipeline test-sites. They'd not have any real traffic hitting them.

> we may also have to do some work to populate the DB when launching a new app

I think there's some facility to clone (maybe with copy-on-write?) the production database for test sites. But I've never actually tried it. Our needs are actually pretty simple; read-only access would be fine, since the regular site never writes to the database (it's only written during the scheduled rake tasks to suck in book/manpage content).

**Comment by jasonlong** [comment]
Since there were no objections to the new direction and with @tarebyte and I working on the updates, I think it's safe to close this. We can take up further logistics discussions separately.

**Comment by jasonlong** [comment]
New project board here: https://github.com/git/git-scm.com/projects/2

**Comment by dscho** [comment]
@jasonlong I really like what you did there. Would you be game to do the same responsive work for Git for Windows (https://github.com/git-for-windows/git-for-windows.github.io)? (The current version was made "responsive" by myself, and my level "Inept" at web design shows...)

**Comment by jasonlong** [comment]
@dscho Doing this responsive work has meant starting from scratch with all new CSS. My focus is going to be on this side project for a while, so I can't guarantee if/when I'll have cycles to help on the Windows site. If nothing else, maybe someone else in the community can take what we end up with here as a foundation for that site.
