### ISSUE TITLE
Manpages are still stuck at v2.16.1

### ISSUE THREAD

**Issue by jnavila** [git/git-scm.com#1153]
v2.16.2 is now more that 10 days old, but git-scm only shows manpages for v2.16.1

**Comment by peff** [comment]
How are you measuring this?

I see v2.16.2 at https://git-scm.com/docs/git-cat-file, for instance. I think there's a bug (or maybe lack of feature :wink:) on the display side that says "v2.16.1" for files that were not updated in v2.16.2 (e.g., https://git-scm.com/docs/git), when it could say "v2.16.2 (last updated in v2.16.1)".

**Comment by jnavila** [comment]
That's it! That's not very intuitive.

**Comment by peff** [comment]
Agreed. I'm not sure exactly what the bug is, though. If I run the "latest version" query manually against the production database, it seems to give sane results:

```
git-scm::DATABASE=> select doc_files.name,versions.name from doc_files
  join doc_versions on doc_files.id = doc_versions.doc_file_id
  join versions on versions.id = doc_versions.version_id
  where doc_files.name = 'git'
  order by versions.vorder desc limit 5;

 name |  name  
------+--------
 git  | 2.16.2
 git  | 2.16.1
 git  | 2.16.0
 git  | 2.15.1
 git  | 2.15.0
```

(AFAICT the actual query just does `limit(1).first`, which should pick 2.16.2). But the doubly weird thing is that it seems to work correctly in my local development environment. So I'm not sure what's different in production.

**Comment by peff** [comment]
Aha. I just flushed the redis cache on production, and the problem went away. So there is something about how the cache key for the page is constructed that does not cause it to be invalidated when we bump the version. I know next to nothing about how that caching works (I think it's all implicit Rails magic).

(Note that you won't see the fix on https://git-scm.com due to the cloudflare caching, but you can see it already on https://git-scm.herokuapp.com).
