### ISSUE TITLE
Get Heroku staging environment set up

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1165]
@pedrorijo91 Adding this tracking issue to pick up the discussion that began at https://github.com/git/git-scm.com/issues/1143#issuecomment-367045485.

It sounds like Heroku Flow would be nice for deploying branches for testing. @tarebyte may be another resource that could help with this I believe.

**Comment by jasonlong** [comment]
Oops, I see there's already an issue for this at #1159. Let's close this one or that one and made sure the remaining issue is attached to the [Site modernization project](https://github.com/git/git-scm.com/projects/2).

**Comment by pedrorijo91** [comment]
I haven't find much time to look into this, but I will try to find some time soon so it doesn't block your work :)

**Comment by jasonlong** [comment]
No worries @pedrorijo91, just wanted to start keeping track of all the tasks swirling in my head. I'm not currently blocked at all – just looking forward to having a place to show progress once we have time to figure it out.

**Comment by pedrorijo91** [comment]
@peff we need to create a pipeline, but it needs to be done by someone with "admin rights" on this repo. Can you do that part? https://dashboard.heroku.com/pipelines/new?org=git-scm

I suppose after that I can configure the pipeline, but if I lack some permission I will tell you

**Comment by pedrorijo91** [comment]
just so that this info don't get lost:

* it seems we need to create a pipeline as described on: https://devcenter.heroku.com/articles/pipelines
* we need to add an `app.json` file to the repo
* the app.json should specify the add-ons for review apps: https://devcenter.heroku.com/articles/app-json-schema#addons
* the review app can use the 'production' database by using inheried config vars https://devcenter.heroku.com/articles/github-integration-review-apps#inheriting-config-vars

**Comment by jasonlong** [comment]
> the review app can use the 'production' database

🎉 Yay! This will be nice. And low/no risk since it's read-only.

**Comment by pedrorijo91** [comment]
This was the app.json file the heroku GUI generated: https://github.com/git/git-scm.com/commit/49c8b1c87c9b127e7b028cd6befac5cd656ea4e7

At this moment the review app is not automatically created (we need to go to heroku and ask for a deploy). It's easily changed on https://dashboard.heroku.com/pipelines/4876d313-a94b-4f65-979a-6cfb92280f77 (1 click) if we prefer that way.

During the setup I found the problem on #1175

**Comment by pedrorijo91** [comment]
@jasonlong / @tarebyte you need to rebase with master to get the commit which introduces the app.json file, and you should be ok to create the review app. let me know if you need any help

**Comment by jasonlong** [comment]
Thanks @pedrorijo91. I'm part way through some rebase conflicts, but will try to wrap that up soon (and not go so long between future rebases).

Once I push `v2` with the new `app.json`, will a new review app spin up? Do we know what the url will be?

**Comment by pedrorijo91** [comment]
review apps are only spin upon PRs. At this moment we need to go to heroku and start the review app manually (this can be done automatically if we prefer - it's easier, but I was afraid due to increasing costs).

On this test pr (https://github.com/git/git-scm.com/pull/1174), the app was deployed at https://git-scm-pr-1174.herokuapp.com/

**Comment by jasonlong** [comment]
@pedrorijo91 I got `master` merged into `v2` and those changes pushed up. Would you be able to start the review app for that branch? Anything else you need from me to make that happen?

**Comment by jasonlong** [comment]
I think we're good to go now. :zap:
