### ISSUE TITLE
I have a problem with "stash" in the windows version

### ISSUE THREAD

**Issue by lyingfromyou** [git/git-scm.com#1191]
![1](https://user-images.githubusercontent.com/24619864/37821760-73602688-2ebf-11e8-947a-bc1c4935f2a2.png)
![2](https://user-images.githubusercontent.com/24619864/37821777-7ecd56b2-2ebf-11e8-83ad-4f1eb1848527.png)
![3](https://user-images.githubusercontent.com/24619864/37821781-80724edc-2ebf-11e8-9ab7-5a6c49236871.png)
![4](https://user-images.githubusercontent.com/24619864/37821783-818a00d0-2ebf-11e8-8927-c91c2a37b9c0.png)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

furthermore, please include a detailed explanation instead of a couple of images
