### ISSUE TITLE
mailing list browser

### ISSUE THREAD

**Issue by schacon** [git/git-scm.com#12]
gmane is just goddamn awful.  

have a sane email list interface for the git ML that is searchable through git-scm, filterable, permalinkable and possibly postable (perhaps authing through google or github)

**Comment by pedrorijo91** [comment]
I would say this issue is not relevant anymore.

the git ml (https://public-inbox.org/git/) is searchable, even if the other features are not present. Since we want to migrate this website into a (mostly) static content, and this goes in the opposite direction, I would vote to drop this feature.

If the git ml lacks some features/usability, we should think about finding a replacement for the git ml itself. (Most of the features are available on email clients like gmail)

I don't use the ml frequently (I'm more of a passive reader), but it seems to me this is not interesting anymore.

closing it, feel free to open if I'm wrong @peff
