### ISSUE TITLE
Implement section anchors in non-man pages

### ISSUE THREAD

**Issue by waldyrious** [git/git-scm.com#1246]
This is a follow-up to #1166, which was implemented in #888. It would be nice if section headers in non-man pages (e.g. https://git-scm.com/community) were linkable.

Given the ongoing work on v2 of the website, it probably makes sense to integrate these anchors in the new design, as @peff commented in #1166.

**Comment by pedrorijo91** [comment]
cc @jasonlong

**Comment by jasonlong** [comment]
Added to the [project board](https://github.com/git/git-scm.com/projects/2?fullscreen=true) backlog.

**Comment by phil-blain** [comment]
This would also be really helpful for the book!

**Comment by hoijui** [comment]
Ahh... indeed they exist! strangely though, they are not constructed in the same way they are constructed in Markdown by default.

In Markdown, the header with text "The Git Protocol" would become "#the-git-protocol",
but here we get ["_the_git_protocol"](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols#_the_git_protocol).

**Comment by dscho** [comment]
Let's just close this, there has not been enough activity to merit keeping this ticket open.

**Comment by waldyrious** [comment]
@dscho I don't understand the closure — multiple people have expressed interest in this feature. Is this no longer desirable?

**Comment by dscho** [comment]
@waldyrious it was closed as _stale_, because nobody felt strongly enough to _do_ anything about it.

As to whether it is desirable: It depends whether you measure desirability in terms of number of people who express wishes vs number of contributions (concrete implementation ideas, experiments, Pull Requests).

Personally, I see negative value in keeping tickets open that languish for years without anybdy feeling strongly enough to kick into action. It is demotivating for everybody involved, and it sets precedents: Some readers will get the impression that the project is dead, others will get the impression that it is okay to demand features and then sit back and expect ["someone else"](https://en.m.wikipedia.org/wiki/Somebody_else%27s_problem) to work on them, a sure way to asphyxiate any open source project.

So where does that leave this here ticket? It is closed, that's true. Is it closed for good? No, not at all. It merely takes but a little action of someone who desires these anchors.

You, for example seem to be motivated.

This action could be in the form of documenting (even in this here ticket) how the anchors in manual pages work, and then outlining what work needs to be done to transfer this functionality to the other pages.

Of course, it is only a very small step from there to actually [verify locally](https://github.com/git/git-scm.com/?tab=readme-ov-file#local-development-setup) that this idea works as desired, and then to open a Pull Request.
