### ISSUE TITLE
standardize the external books list

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1295]
On https://git-scm.com/doc/ext we have a books listing. Most of the items respect an undocumented format, but it seems that we have a few that do not:

- Git in the Trenches, which adds a 'creative commons' kinda of watermark bellow the author name
- Git Internals Peepcode PDF, has the same issue, plus a smaller image

Is there any (good) reason to have the creative commons watermark? Can we remove it? Seems to have been introduced a while ago https://github.com/git/git-scm.com/commit/05cde2511a173513b2ad91e01da3266dafcde267

**Comment by peff** [comment]
I think it's nice to promote "open" books more, since the community can improve and reuse them (and certainly Pro Git has special status there, due to its community involvement). So I don't mind having a special mark. But I certainly don't think it's something we've applied consistently (i.e., for ones not marked with the CC mark, I have no idea if that's because they're not CC or if it's because nobody bothered to put in the mark).

So I'd be OK with keeping or dropping it. In an ideal world, we'd dig out the license for each resource we link to and organize or mark it accordingly. But I don't know if that's worth the manual effort involved.
