### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by schacon** [git/git-scm.com#13]
we should have a blog - detailing new releases and what's in them, as well as pointing out interesting things in the git community

**Comment by gmarmstrong** [comment]
Had to dig around for this: https://git-scm.com/blog.rss
It would be nice to have a link to the feed in the blog's footer!

**Comment by pedrorijo91** [comment]
It could be nice, but the blog has no new content for a long time @gmarmstrong, and AFAIK there's no plan to restart it

**Comment by jnavila** [comment]
We could post the git rev news on the blog.

**Comment by peff** [comment]
I'm not sure if revnews is of general interest to Git users, as opposed to people involved in development.

Still, I'd be happy to provide links if revnews folks are interested (/cc @chriscool @tfnico @jnareb). I'm not sure if the blog (which I'd really like to just kill off) makes sense, though. I'd rather just have a link under the community page so that people can subscribe to revnews separately if they want.

**Comment by pedrorijo91** [comment]
yeah, rev news is already posted in https://git.github.io/rev_news/, and as @peff mentioned, most users don't bother about most of the subjects discussed there..

**Comment by pedrorijo91** [comment]
closing this issue as there are no plans nor content for the blog
