### ISSUE TITLE
cannot download git for windows

### ISSUE THREAD

**Issue by cc3859** [git/git-scm.com#1333]
I have Windows 7 Home Premium Service Pack 1 64-bit and AT&T DSL 1.5 MB and I require Git to complete Udacity Nanodegree.  I cannot load Git for windows. Receive Access Forbidden <Error> <Code>AccessDenied</Code> <Message>Request has expired</Message> <X-Amz-Expires>300</X-Amz-Expires> <Expires>2019-03-30T13:10:59Z</Expires> <ServerTime>2019-03-30T13:22:00Z</ServerTime> <RequestId>0082A274B3AE5897</RequestId> <HostId> ektUT4B/tzLnsnLOlHK45OeKOppps3SyMCXyEjtFXlbyX5bkV+psA4tNyRV//tko0BKGXhrtVqM= </HostId>

**Comment by pedrorijo91** [comment]
what have you tried? I assume you tried one/some/all the links at https://git-scm.com/download/win ?

It may be due to some browser/extension thing. Can you try with different browsers and/or incognito mode?

**Comment by cc3859** [comment]
Yes, I tried  https://git-scm.com/download/win for 32 and 64 bit. I tried IE, Chrome and Fox browsers.

**Comment by cc3859** [comment]
I also tried incognito mode

**Comment by cc3859** [comment]
Right now I'm trying GitHubDesktopSetup.exe https://desktop.githubusercontent.com/releases/1.6.5-b8b05c40/GitHubDesktopSetup.exe

**Comment by pedrorijo91** [comment]
can you try in another machine? it's working for me, so at first sight may be a problem at your end

**Comment by cc3859** [comment]
Is it something with my Windows 7 Home Premium?  Is there another version of Git that would work with that?

**Comment by cc3859** [comment]
I tried another machine Acer and Dell laptops.

**Comment by cc3859** [comment]
![image](https://user-images.githubusercontent.com/49096473/55277190-3e629e80-52cb-11e9-9d2e-1d6aa02e0088.png)

**Comment by cc3859** [comment]
I don't know if the root cause is because my AT&T DSL is slow and the link is set to expire at 300, because I have Windows 7 Home Premium or if I am being denied access for another reason. I've loaded applications much larger than 44 MB.

**Comment by cc3859** [comment]
I did go into Git and signed up, thinking it was a security issue on the Git side.

**Comment by im-singh** [comment]
I think my issue is a little bit related with this. I tried many time to download git for Windows but the download speed is so slow like 7 hours to go for just 100mb. My internet connection is good. Can anybody help me. If there is any other resource available tell me..

**Comment by Balls0fSteel** [comment]
Same here. 1/1gbps FTTH connection. Testing 1000/1400-2000 speeds.

Yet... git-scm downloads with 15-30kbps. A JOKE.
Please fix?

**Comment by ahellbach** [comment]
I had the same problem, the download was very slow. 
The solution was to install git via chocolatey.

**Comment by Balls0fSteel** [comment]
I mean the devs/project would only need to offer mirrors somehow. I realize it's part of Github, so maybe Github could let us pick a mirror? Sourceforge had auto and hand-select mirrors for decades and it works superb. 

Cause I understand, it might be a temporary peering or routing problem. Maybe a spat between ISPs. These things happen and I do not care. No one should. That's why hand-selected mirrors are still a thing elsewhere, cause you can just try something else.

Ps.: I used a VPN in the end to download....

**Comment by peff** [comment]
To be clear, this issue is not likely to go anywhere useful because you are several steps removed from anybody who can do something about it. The git-scm.com page is just linking to the Git for Windows project's releases. They host artifacts through GitHub's Releases mechanism (which is a Git for Windows decision), which are then served by Amazon S3 (a GitHub decision). At the point you're experiencing slowness, it's just your browser talking to S3.

I suspect it would be more productive to talk to GitHub support about slow Releases downloads (they probably can't _fix_ it if it's an S3 problem, but that at least makes them aware of it).

**Comment by joecar7** [comment]
I'm still seeing the super slow download of the git installer, it never completes,

**Comment by Balls0fSteel** [comment]
Honestly, they would just need to give us a mirror selector like Sourceforge - for example. It's that simple. And yes the problem still exists. Very annoying to wait hours for a few megabytes.

**Comment by pedrorijo91** [comment]
Exposed the problem to git-for-windows team: https://github.com/git-for-windows/git/issues/2443

 Let's see if we can find a solution together

**Comment by JacquesInnocent** [comment]
I managed to download git from Softonic pretty faster here (https://en.softonic.com/download/git/windows/post-download)

**Comment by pedrorijo91** [comment]
hey @JacquesInnocent . thanks for adding your suggestion!

But from what I can see, that link will download git 2.14.2, and the latest version is already 2.24.1. Can you confirm the version you downloaded from that link?

**Comment by dscho** [comment]
> that link will download git 2.14.2

😨 oh no! There have been _two_ critical updates since that version: https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version

**Comment by sarang-upadhye** [comment]
After opening in Incognito Mode, it works fine!

**Comment by pedrorijo91** [comment]
for anyone else experiencing this issue: look at the discussion https://github.com/git-for-windows/git/issues/2443#issuecomment-671403695 

it seems possible to download snapshots directly from https://wingit.blob.core.windows.net/files/index.html as well, which may be a good workaround

**Comment by adsingh14** [comment]
Every link is working for Windows setup. I think this issue should **closed**.

**Comment by peff** [comment]
Closing as stale / outside the scope of the git-scm.com site.
