### ISSUE TITLE
Download version always slower

### ISSUE THREAD

**Issue by Nothing-Works** [git/git-scm.com#1354]
![screenshot-git-scm com-2019 06 09-17-20-14](https://user-images.githubusercontent.com/18606648/59155327-005bd500-8adb-11e9-8b69-05f820eb8109.png)

For some reason, I always need to wait for a few days to download the latest version. 
The latest version was released on 2019-06-07, it's 2019-06-09 and still, I can only download the old version.

Actually, this is the same for Mac
![image](https://user-images.githubusercontent.com/18606648/59155611-5b90c600-8ae1-11e9-9c9d-a205e683136c.png)

**Comment by pedrorijo91** [comment]
hey @Nothing-Works 

git for mac and windows are different projects. As such, someone needs to port updates into those codebases. Thus it's normal that it may take some time, which is generally a few days.

I believe this is not normally a problem (is there any new feature that important that an user can't wait a few days?). If that's the case, I believe the only viable solution is to support those projects, either monetarily, or by contributing directly with code patches:

- git for mac: https://github.com/timcharper/git_osx_installer/
- git for windows: https://github.com/git-for-windows/git

**Comment by peff** [comment]
The OSX installer often lags by quite a bit, but @dscho is very quick these days about releasing Git for Windows (usually the same day). There's some additional lag because the site picks up the new downloads nightly (though I usually prod it manually when I see the release come out), and then a bit of caching on the cloudflare side. I did just prod it and we should be linking to 2.22 for Windows now.

**Comment by dscho** [comment]
@peff maybe I could help you set up e.g. an Azure Function that does this prodding, with a PAT that my Git for Windows automation could use to trigger it whenever a new official version comes out?

Not sure whether it is worth it, at most it seems that the indicated lag is a day or two, which does not matter in the big picture.

**Comment by peff** [comment]
@dscho Thanks for the offer, but I think it's a little complicated on our side due to the access model. There's no HTTP end-point to hit that would trigger an update (nor anything in general that is not read-only, which I'd prefer to keep as we consider moving to a more static deployment). The updates are triggered by a `rake` job which is kicked off by the equivalent of `cron`, but there's no easy way to trigger that externally.

It _would_ be easy to just schedule the `downloads` check more frequently. We'll always pick up the release within 24 hours, but we could drop that to (say) 4 hours pretty easily. I don't think the cost of a noop check is very high.

**Comment by dscho** [comment]
> It _would_ be easy to just schedule the `downloads` check more frequently. We'll always pick up the release within 24 hours, but we could drop that to (say) 4 hours pretty easily. I don't think the cost of a noop check is very high.

Can I do anything to make that cheaper?

One thing you might not know yet is that https://gitforwindows.org/latest-version.txt is always updated with the latest release... and https://gitforwindows.org/latest-tag.txt, too... (and of course, this converts to https://github.com/git-for-windows/git-for-windows.github.io/blob/master/latest-version.txt and https://github.com/git-for-windows/git-for-windows.github.io/blob/master/latest-tag.txt, if that makes a difference...)

**Comment by peff** [comment]
> Can I do anything to make that cheaper?

I don't think so. It's basically just hitting the GitHub releases API (and it wants to idempotently backfill any tags, so it gets the whole list instead of just caring about the latest; though I suppose if we wanted to be really clever we could use the "latest" as a canary that tells us there's something to fetch). Anyway, it really seems like starting up a dyno and running `rake` takes longer than the actual network request. I just bumped it to be an hourly job.

I didn't do the same for the `preindex` job, which picks up new documentation, as it's quite a bit more expensive. Unfortunately this is also the job that creates the new-version records that feed the "latest version" box on the main page. So we could still have some lag when a new Git version comes out, though I tend to be watching those anyway and trigger a manual update.

In the long run, this probably ought to be triggered by a hook when the tag gets pushed to git/git (either by GitHub webhook, or something like an Azure Pipeline). I think the whole architecture would be a lot simpler if we finished the conversion to a static site, built and deployed it from something like Azure Pipelines, and then just triggered builds as appropriate when our dependencies updated.

I don't think it's urgent to get there, though, as the current polling system works _pretty_ well, and is consistent within a reasonable time period.
