### ISSUE TITLE
'ls-tree' is missing from reference page

### ISSUE THREAD

**Issue by ruifortes** [git/git-scm.com#1375]
Hello.
'git ls-tree' is missing from command reference.
Is this intentional for any reason? Is it a deprecated method?
Sorry not to PR but I don't know ruby

**Comment by ruifortes** [comment]
I guess you can do it with `git cat-file -p master^{tree}`
`git cat-file tree master` output something binarish

Is cat-file the preferred method?

The cat-file reference is doesn't mention the weird '^{tree}` syntax.

Can someone point me to a more in-depth () documentation on this?

**Comment by peff** [comment]
> 'git ls-tree' is missing from command reference.
> Is this intentional for any reason? Is it a deprecated method

No, it's not deprecated. There are a lot of somewhat useless historical commands, so the command list on the site started as "here are the most useful commands". And then we've added to that over time as people notice useful things missing. I think `ls-tree` should be on it, in the plumbing section. It should be a one-liner to add it to https://github.com/git/git-scm.com/blob/2218df63fb87028d39a38e4c64ed7ba10b70f056/app/views/shared/ref/_plumbing.html.erb#L9-L13

> Is cat-file the preferred method?

No, `ls-tree` is the recommended way to get a tree listing.

> The cat-file reference is doesn't mention the weird '^{tree}` syntax.

That's because it's not specific to `cat-file` at all, but is part of Git's [object-name syntax](https://git-scm.com/docs/gitrevisions).

**Comment by ruifortes** [comment]
Thanks
