### ISSUE TITLE
More than one sub-section highlighted in Chapters drop-down menu

### ISSUE THREAD

**Issue by josecarlus** [git/git-scm.com#1490]
If a user is currently at a sub-section whose name displayed in the Chapters drop-down menu is identical to other sub-sections (e.g. Summary, Maintaining a Project, etc.), then all sub-sections with this name in the menu appear highlighted.

![Capture](https://user-images.githubusercontent.com/13310685/87865689-b64d5000-c978-11ea-90d7-d8010bd9f102.PNG)

**Comment by pedrorijo91** [comment]
thanks for reporting the issue @josecarlus !

indeed it seems a bug. I would say the problem is at https://github.com/git/git-scm.com/blob/master/app/views/books/_chapter_listings.html.erb#L15, when we compare the content title with the section title. We should probably compare both numbers.

Would you be interested in doing the fix? :)
