### ISSUE TITLE
All available languages of a given manpages do not show up for all languages

### ISSUE THREAD

**Issue by jnavila** [git/git-scm.com#1518]
In the manpage of `git init`, if you look at the available translations, from English, you get 5 languages. Now, click on the latest language of the list (简体中文) and reopen the language list. Now there are 7 languages!

### URL for broken page
https://git-scm.com/docs/git-init/zh_HANS-CN
https://git-scm.com/docs/git-init/

### Problem
It seems that the list of available languages is not refreshed when new languages are added: the missing languages are the latest ones and they are missing in the pages of the older ones.

I checked directly on Heroku. Although I remember we removed all caching at this level, I suspect something similar. The code in charge of building the list of languages seems benign:

https://github.com/git/git-scm.com/blob/22a1763d1c72f9388f6870b376652fd364bd99e6/app/views/doc/_languages.html.erb#L4-L12

So, I have not idea where this might come from, except bad caching.

**Comment by peff** [comment]
@jnavila I think you're right. I dropped the rails level cache (by running `heroku redis:cli`, and then issuing a `flushall` command) and that seems to have fixed it. I'm not sure how the caching keys work here. There's probably a way to make it so that the cache validity depends on the languages list, but I'm not sure how. An alternative is that we might consider flushing caches nightly after running the doc build jobs, though it feels a little wasteful (we'd probably get a load spike shortly thereafter as we refill the common cache hits).
