### ISSUE TITLE
ProGit2 migration Asciidoctor 2.0.11 causing rendering issue with HTML build

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1530]
## Current behavior:

Monospaced text with gray highlights appearing in illogical places.

## Expected behavior:

Monospaced text with gray highlights are in logical places.

## Steps to reproduce:

1. Go to https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches
1. Search for string `this is a bit` to go to the relevant parts.
1. See mono-spaced font and gray background apply to the wrong part of the sentences.

Also do:

1. Go to https://git-scm.com/book/en/v2/Git-Branching-Rebasing
1. Search for string `This basically says`
1. See sentence has bad monospaced font and gray background in illogical place.

## Context:

I first though I had done something wrong with the migration to Asciidoctor 2.0.11 in the source files at the ProGit2 repository. However it turns out that the ProGit2 HTML and PDF output are fine.

I think this is a problem with the `git-scm.com` HTML build process???

## Picture of bug on `git-scm` site:

![broken_quotes](https://user-images.githubusercontent.com/34918129/98528892-36c3f380-227d-11eb-8324-5148b21e17c3.png)

## ProGit2 PDF output:

![progit2_pdf_is_fine](https://user-images.githubusercontent.com/34918129/98530789-b357d180-227f-11eb-843e-cfa55e5b8a44.png)

## ProGit2 HTML output:

![progit2_html_output](https://user-images.githubusercontent.com/34918129/98531072-177a9580-2280-11eb-9a44-d7fa90ca8f02.png)

## Reference to original issue at ProGit2 repo:

See https://github.com/progit/progit2/issues/1557

**Comment by HonkingGoose** [comment]
I think I found a possible cause, ProGit2 uses Asciidoctor `2.0.11`, but git-scm.com uses `2.0.10`.
I think that this might be fixed by upgrading your `Gemfile.lock` to use the newer version of Asciidoctor?

## Git-scm HTML build script:

https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake

## Git-scm gemfile

https://github.com/git/git-scm.com/blob/master/Gemfile

## Git-scm gem lock file:

https://github.com/git/git-scm.com/blob/a52b716cfe0be5fbd37b31212311d2fdb461903f/Gemfile.lock#L41

## ProGit 2 gemfile:

https://github.com/progit/progit2/blob/master/Gemfile

**Comment by jnavila** [comment]
It's more related to

 https://github.com/git/git-scm.com/blob/a52b716cfe0be5fbd37b31212311d2fdb461903f/lib/tasks/book2.rake#L86

Where compatibility mode is forced. The issue here is that script is also used to build the translations which have not migrated to modern asciidoc.

**Comment by peff** [comment]
I believe there's a way that the documents themselves can say "I expect compat mode". That would be the ideal solution,since then as translations moved to the more modern syntax, they could unset that flag. But I suspect the defaults don't work well for us: the default is non-compat, and the document can trigger compat-mode. But that would mean that the translations would have to all update to insert that trigger, and the likely problem here is that some translations will be stragglers (or maybe not? At least inserting "use compat mode" is less work than merging the syntactic changes into the translated text).

A more coarse option is us maintaining a list of which translations need compat mode and which doesn't. I'm not excited about that, because it means that as the individual translations shift, we'll have to remember to drop their compat-mode flags.

The coarsest option is to just drop compat-mode entirely. That will fix the main version and break all of the translations until they update. That _might_ not be too bad. I'd imagine the English version is the most-read, and it would mean that the translations will all eventually converge on correctness. But I may be showing my English-centrist view here.

**Comment by HonkingGoose** [comment]
Lifted from https://asciidoctor.org/docs/user-manual/#builtin-attributes

| Attribute name | Description | Default value| Allowed values | Header only | See also |
| --- | --- | --- | --- | --- | --- | 
| compat-mode | Controls whether the legacy parser is used to parse the document. | `not set` (Modern parser is used). | `empty` (Legacy parser is used). | | [Asciidoctor docs, Migrating from AsciiDoc Python](https://asciidoctor.org/docs/user-manual/#migrating-from-asciidoc-python) |

**Comment by peff** [comment]
@HonkingGoose Yeah, but the book content has to then set that attribute for it to help us. The translations can set it to `empty`, but presumably that will take a while. Possibly the English version could _unset_ it. I'm not sure if we can unset an attribute like that from within a document. I think just flipping our default (as in #1532) is a reasonable solution, and we can let translations catch up with the changes (or set the compat-mode attribute themselves).

**Comment by peff** [comment]
I merged #1532 and rebuilt the book content; the example you gave above looks fixed now (I checked by hitting heroku directly; you may see the old content for a few hours via the cdn). I'm going to close this, because I think it's good enough for now. If we find that translations are slow to pick up the new content, then we can think about addressing that (but I think my preference would still be for them to mark their content as needing compat, which would be PRs in their repos, not here).

**Comment by HonkingGoose** [comment]
@peff and @jnavila thanks for fixing this. I think the solution you chose is a good one.
