### ISSUE TITLE
Add a link to download MinGIT on Git downloads.

### ISSUE THREAD

**Issue by pratikpc** [git/git-scm.com#1536]
https://github.com/git-for-windows/git/releases

Git for Windows now also distributes MinGit where they reduce some of the bloatware Git has

It would be nice to see MinGit mentioned here https://git-scm.com/download/win

[An article on MinGIT](https://devblogs.microsoft.com/devops/whats-new-in-git-for-windows-2-10/)

Please ONLY submit issues related to the git-scm Website (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly) !

Make sure this is NOT an issue about :

     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with https://git-scm.com/docs), which should be raised with the community at https://git-scm.com/community,
     - the contents of the Pro Git book (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at https://github.com/progit/progit2/issues.
     - Git itself, which should also be raised with the community at https://git-scm.com/community, or
     - Git for Windows, which should be raised at https://github.com/git-for-windows/git.

**Comment by pedrorijo91** [comment]
hey @pratikpc 

I'm not sure we should add MinGit:

> MinGit: Git for Windows applications
> The idea is to provide a version of Git for Windows that does not provide an interactive user interface (...)

so it doesn't seem to be very useful or user-friendly at least for *most* Windows users

furthermore:

> Another big new feature since Git for Windows 2.8 is MinGit: with every new Git for Windows version, we now offer .zip archives of “Git for Windows applications”.

so it seems to come included? Not sure if your suggestion is to have another link to download just MinGit or just to add a quick sentence letting users know about MinGit?

**Comment by pratikpc** [comment]
> so it seems to come included?

Sadly, no. Windows isn't that generous yet. It's an article from the Azure Devops team so I presume at one point they did provide Mingit pre-installed with one of the Azure CLI binaries. I actually put the link there because [there is another mingit project that does something completely different](https://github.com/evansendra/mingit) and I did not want to cause major confusion.

> so it doesn't seem to be very useful or user-friendly at least for most Windows users

That is indeed true. I think a lot of Windows users install Git not just for Git but also for Git Bash and other utilities. But I, on the other hand really wasn't very interested in the other utilities. For example, I prefer Notepad for interactive rebase over the default which is vi I think and didn't want Gitk (I prefer GitHub Desktop and GitKraken more).

Mingit does ship with a lot of Linux utilities like wc, awk, cat etc.

> Not sure if your suggestion is to have another link to download just MinGit or just to add a quick sentence letting users know about MinGit?

I was thinking about a download link but yeah, a quick sentence would be nice too! Something like _You can use Mingit if you want a smaller binary and don't want Git-Bash etc._.

**Comment by pedrorijo91** [comment]
sorry, totally missed your reply. not sure what's the current status of MinGit, but if you see it's still a good solution, feel free to create a MR @pratikpc :)

**Comment by plashenkov** [comment]
I'm glad I've found MinGit. Even PortableGit requires some strange actions like post-install.bat, etc. While MinGit doesn't (well, it looks so). All I need is to use git in VS Code and run basic commands from command line, like `git clone`, etc. It would be great if info about MinGit was more visible.

**Comment by dscho** [comment]
👋 from the Git for Windows maintainer.

MinGit is indeed not intended for end users, and advertising it to end users in spite of this would only have the effect of many users asking for more features, essentially asking for MinGit to become PortableGit. Therefore, going through with this idea would increase the maintenance burden, which I would prefer people to be less enthusiastic about, honestly.

**Comment by pratikpc** [comment]
@dscho makes sense

**Comment by dscho** [comment]
I'll close this ticket fore aforementioned reasons.

**Comment by YasharF** [comment]
For anyone that gets to this Github issue from a search engine because they are trying to figure out how to install MinGit easily and keep it up-to-date, and they want MinGit specially because they only need a minimal git CLI in the Windows terminal, you can install it with winget.  In Windows CMD (Run as Administrator) run:

`winget install git.mingit`


Git for Windows project releases the MinGit version with their every release along with other variants such as the full version and the portable at https://github.com/git-for-windows/git/releases ; there is a bot that keeps the winget manifest up-to-date when there is a release.  The winget manifest gets updated to point to the Github release such as in https://github.com/UnownPlain/winget-pkgs/blob/ea8d0d5985604f21638b4b510dcbe9e6bd170018/manifests/g/Git/MinGit/2.54.0/Git.MinGit.installer.yaml  ; if the manifest doesn't get updated in the future because of a broken automation or something, you can step up and use [wingetcreate](https://learn.microsoft.com/en-us/windows/package-manager/package/manifest) to submit a PR to the winget repo to add the new version.

Tip: To add a basic editor if you need to edit commit messages and not just fetch/pull stuff from external repos, add notepad or similar to your gitconfig (aka `C:\Users\YourUsername\.gitconfig` like the following.  Make sure to "save" your commit message in notepad if you are changing what pops up.
```
[core]
	editor = "\"C:\\Windows\\system32\\notepad.exe\""
```

**Comment by dscho** [comment]
And let it be know to anybody who finds this, let's say, well-intentioned advice: _any_ interactive use of MinGit that works today may very well be broken tomorrow. If that happens to you, your only recourse will be to understand that this was your own choosing. That you _chose_ to use MinGit _outside_ of what it supports, and that you're not allowed to open a ticket about this because you have been warned that this is outside the supported use cases.

Seriously, my life as Git for Windows maintainer is hard enough without people asking to make MinGit interactive and basically turn it into full Git for Windows, but please without making it larger thankyousomuchbye.
