### ISSUE TITLE
Still failing to pick up changes in books sources

### ISSUE THREAD

**Issue by jnavila** [git/git-scm.com#1540]
I updated some books but it seems the caching of the website  is still preventing the changes from appearing. The site on Heroku is not updated also. Did the change in the logic of detection of update introduce a regression?

**Comment by peff** [comment]
It looks like we haven't been doing updates properly for the past week or two due to a change on GitHub's side. Should be fixed by #1541. I'm running the nightly job now, so let me know if you don't see the updates you're expecting after it's had a chance to run.

**Comment by peff** [comment]
By the way, I wish we really had a way to know about failed jobs. Our update jobs have been failing for two weeks without any indication. Unfortunately Heroku's scheduler gives you _nothing_ in the way of output, not even a single success/fail bit. You're supposed to do your own rails-level logging, and/or send an email, but we don't have either of those set up (since aside from the periodic rake jobs, the site is essentially static).

I guess another option would be to trigger them from a schedule GitHub Action. That would mean an extra layer of credentials, though (GitHub has to trigger `rake` on Heroku, which then triggers API lookups on GitHub). This would all be a lot easier as a single static site build. :sweat_smile:

**Comment by jnavila** [comment]
Updates are online! Thanks a lot!
