### ISSUE TITLE
broken / circular bug report links

### ISSUE THREAD

**Issue by pannous** [git/git-scm.com#1606]
The path for submitting issues with Git program is unhelpful / broken

### URL for broken page
https://git-scm.com/community
https://github.com/git/git-scm.com/issues/new/choose

### Problem
Trying to report an issue in git; found https://git-scm.com/community which suggests
1. `git bugreport`

This does not work:
```
~/ git bugreport
~/ git: 'bugreport' is not a git command. See 'git --help'.
~/git --version 
~/git version 2.23.0
```

2. https://github.com/git/git-scm.com/issues

Trying to report an issue in git:
https://github.com/git/git-scm.com/issues/new/choose
'Problems/questions/bugs about Git program'
Links back to the first URL

**Comment by pedrorijo91** [comment]
Hey @pannous ,

1. On the page you mention we can read:

> If you are using git 2.27.0 or later, you can run git bugreport (...)

and it seems you are using an older version which doesn't have that new command yet


2. Regarding this: it links to the webpage because this repo is for reporting issues about the website, not git program itself. On that page its said:

> Bugs in git can be reported directly to the mailing list

Have you tried that option?

Thank you
