### ISSUE TITLE
Pro Git 2  book page introduction missing

### ISSUE THREAD

**Issue by wohenbushuang** [git/git-scm.com#1611]
In Pro Git 2, there is a brief [introduction](https://github.com/progit/progit2/blob/master/book/introduction.asc) for each chapters, and I can't find it on the website [http://git-scm.com/book/en/v2](). I wish this introduction can be provided on the website, it will help readers a lot.

**Comment by pedrorijo91** [comment]
hello @wohenbushuang . You are totally right. While the introduction exists in the pdf version, it doesn't exist in the online/html version for some reason. 

@jnavila do you have any clue on this?

**Comment by jnavila** [comment]
It's "on purpose". At least it was from the beginning, given how the import script on git-scm.com was written. 

This editorial choice was preserved across refactorings, and I think too that the elided parts still don't need to be present on the website because the way the book's content is accessed on the website is more as a result of a query in a search engine, not by a reading from start to end. Ebooks are more devoluted to this use case, even if I suspect it tends to vanish nowadays.

**Comment by wohenbushuang** [comment]
Both is okay for me, as @jnavila said, I used it as a reference book too.

**Comment by pedrorijo91** [comment]
thanks for the input @jnavila . it seems this is a non-issue then
