### ISSUE TITLE
The Monitor Button overflows the monitor

### ISSUE THREAD

**Issue by akmalick** [git/git-scm.com#1620]
### URL for broken page

https://git-scm.com/downloads
https://git-scm.com

### Problem

The page UI for above two urls seems to be broken. If any Windows user visits either of them he/she will notice that the monitor button overflows the monitor itself, as can be seen in the image below :

![image](https://user-images.githubusercontent.com/5765159/124464937-6bf3f780-ddb2-11eb-8b77-79fb957db59e.png)

### Operating system and browser

Operating System : Windows 10.
 Browsers : Google Chrome, Edge, Firefox.

### Steps to reproduce

One just needs to navigate to the above mentioned links from a Windows 10 OS in order to re-produce this issue.

### Other details

I'm not a CSS expert but just tried to play around with the devtools and found that,
when I try and remove the padding, the UI looks fine(except that the button becomes more finer because of removal of padding) :

![image](https://user-images.githubusercontent.com/5765159/124466852-b0809280-ddb4-11eb-9696-cd8d9716b1cb.png)

Or if I keep the padding, but remove the top margin, then also it looks fine:

![image](https://user-images.githubusercontent.com/5765159/124467894-19b4d580-ddb6-11eb-8037-c4809de6462f.png)

**Comment by peff** [comment]
Hmm, yeah, I can see the same thing if I  I think it was never intended to break across two lines of text. In the Linux and Mac buttons, it's short enough to stay as one line and looks nicer. I wondered if shorter versions strings (e.g., `2.1.0`) would make a difference, but they seem to wrap for me, as well (the problem is the word "Windows" is just longer).

Of the two solutions you showed, removing the padding looks better to me. Want to open a PR to fix it?

Some alternatives:

  - shrinking the font-size on the button a bit (to say, 14px) puts it all on one line, even for "Windows"
  - the Linux button just says "Downloads for Linux", since there is no auto-download when you click it (and the version is already given a few lines above). We've talked about getting rid of the auto-download for Windows before, at which point making all of these just "Download for X" would be reasonable.
  - The whole monitor thing is pretty dated, and IMHO just contributes to visual clutter. We could get rid of it, but that would involve some light design work to replace it (since we still want a prominent "this is the latest version, click here to get it" section on the front page).

**Comment by akmalick** [comment]
> Of the two solutions you showed, removing the padding looks better to me. Want to open a PR to fix it?

I'm more than glad to raise a PR. I believe it is more appropriate to get rid of the redundant version from the button. I tried removing it and it looks nice :

![image](https://user-images.githubusercontent.com/5765159/124481998-7c15d200-ddc6-11eb-9523-962d6e9672e0.png)

This would mean I no longer have to disturb the styling/font-size and at the same time ensure that there are no redundant ui elements in same place. 

I believe same can be done for Mac too. 

Also I noticed that for Linux it says "Download**s** for Linux". There's an extra 's'. I believe it needs to be changed to **Download**.

Affected File : [app/assets/javascripts/application.js](https://github.com/git/git-scm.com/blob/main/app/assets/javascripts/application.js)
Affected Lines : 53(version-removal), 60(version-removal) and 69(removal of 's' from **Downloads**).

Should I go ahead with the above changes ?
