### ISSUE TITLE
Singularization/Pluralization GUIs count.

### ISSUE THREAD

**Issue by adsingh14** [git/git-scm.com#1662]
### URL for broken page

https://git-scm-pr-1660.herokuapp.com/download/gui/android

### Problem

When we open Android GUIs page, it has just single entry/item but the phrase is incorrect. 
Currently, it is: `1 Android GUIs are shown below`
Expected: `1 Android GUI is shown below` or don't show the phrase.

### Operating system and browser

OS: Windows 10 Pro
Browser: MS Edge Version 96.0.1054.62 (Official build) (64-bit)

### Steps to reproduce

1. Go to Downloads > GUI Clients.
2. Filter GUIs category to Android.
3. GUIs count will update below tabs.

### Other details

![image](https://user-images.githubusercontent.com/35252877/147594196-aa03a42f-6388-4b68-afc0-3481cb243884.png)

**Comment by pedrorijo91** [comment]
yeah, i don't think we ever worried about that case, looking into https://github.com/git/git-scm.com/blob/3b22d7483cee007d4550c563a99b15a2e39ba4ab/app/views/downloads/guis/index.html.erb#L25

probably because Android/iOS are "[new](https://github.com/git/git-scm.com/commit/44b9431a890d03cd95a3cdc331471b2fb2271291)" categories, and before that we'd have multiple GUIs for each

**Comment by adsingh14** [comment]
Alright! I'm closing this issue because someone will create an Android GUI and some of us will revert the changes.
