### ISSUE TITLE
Automatic publishing of ProGit book is not working.

### ISSUE THREAD

**Issue by Morganov** [git/git-scm.com#1699]
Before migration from TravisCI to GitHub Actions each release of the ProGit book was published at git-scm.com/book/ including translations.

Now, this process seems to be broken - the new changes are not published.

Here is an example:

The PR is merged https://github.com/progit/progit2/pull/1759 and the new version of the book is released https://github.com/progit/progit2/releases/tag/2.1.346 
It is expected that the changes will appear on the page http://git-scm.com/book/en/v2/Git-Branching-Branch-Management but nothing changed.

**Comment by jnavila** [comment]
In fact, the publishing on git-scm.com web site has nothing to do with Github Actions. IIRC, this is a crontab job running each night on the dyno. @pedrorijo91 @ttaylorr could you check the status of the dyno cron scripts?

**Comment by peff** [comment]
I think the cronjobs can't hit GitHub's API because the API token they have is an old one belonging to me, and is expired. Ideally there would be some token belonging to a bot account. Barring that, somebody more active should probably generate a token (with locked-down permissions!) and stick it in `GITHUB_API_TOKEN` in Heroku's config vars (under "Settings", though I think "heroku config" from the CLI can touch the same ones).

**Comment by ttaylorr** [comment]
@pedrorijo91 do you have access to do this? Otherwise, I can take a look into it myself.

**Comment by ttaylorr** [comment]
Done.

**Comment by pedrorijo91** [comment]
sorry @ttaylorr i've been out for the past week. i guess this will solve the heroku apps issue as well
