### ISSUE TITLE
mark Aurees as depricated / development ceased

### ISSUE THREAD

**Issue by Ryder17z** [git/git-scm.com#1848]
it hasn't been updated in years and does not function properly, regardless of OS.

**Comment by pedrorijo91** [comment]
Thanks for letting us know. Would you be interested in contributing by
Adding a PR removing it?

On May 26, 2024, GitHub ***@***.***> wrote:
> it hasn't been updated in years and does not function properly,
> regardless of OS.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/git/git-scm.com/issues/1848>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAPIBSWDOF62KG7PCCRLDOTZEIZJ3AVCNFSM6AAAAABIKBGIM2VHI2DSMVQWIX3LMV43ASLTON2WKOZSGMYTOOBZHEYTQMQ>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by pedrorijo91** [comment]
overlooked this on mobile: just noticed the app did a release less than 6 months ago in December (https://github.com/gitahead/gitahead/releases), and not "in years"

so maybe there's something wrong in the steps u followed and it would be better to raise in the repo directly? @Ryder17z

**Comment by rimrul** [comment]
> overlooked this on mobile: just noticed the app did a release less than 6 months ago in December (https://github.com/gitahead/gitahead/releases), and not "in years"

The README.md in that repo does start with this text, thoug:

> GitAhead is no longer under active development. Low-level maintenance and bug fix releases will be made as necessary for the foreseeable future, but no new features or major changes are planned at this time.

**Comment by Ryder17z** [comment]
I believe this can be closed for now as the pr got merged.
