### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by DiogoAndre** [git/git-scm.com#265]
I'm interested in starting a translation effort for the git-scm website. Are there any current plans or efforts?

cheers

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.

**Comment by codingisacopingstrategy** [comment]
@sxlijin Could you give some explanation on why this is no longer an issue?

**Comment by peff** [comment]
There are three main content sources:

  1. Content original to the site itself (e.g., the landing page).

  2. Content imported from the Git manpages.

  3. Content imported from the Pro Git book.

The third one already has a translation effort ongoing. The second one is outside the scope of this repository (but if a translation project starts, we'd do some work to import them).

I do think the first is within the scope of this repo. However, it's a big project that nobody has moved on at all in the past 3 years since this issue was opened. So it's definitely not "already fixed", and I'm not quite sure it's "won't fix", but it does seem like a stale request.

**Comment by sxlijin** [comment]
Ah, yeah, I was commenting more specifically along the lines of "there are existing translation efforts" (if I'm not mistaken).
