### ISSUE TITLE
Duplicate results in search

### ISSUE THREAD

**Issue by olivierlacan** [git/git-scm.com#346]
When searching for "apply" this is what the site returns:

![image](https://f.cloud.github.com/assets/65950/1848093/143ba62a-767a-11e3-83d2-1a632590a5ac.png)

The two "Stashing" links respectively point to:
- http://git-scm.com/book/en/git-tools-stashing
- http://git-scm.com/book/en/Git-Tools-Stashing

So the duplication appears to be due to capitalization of the paths. Not sure what's going on there. This only seems to happen with Book results.

**Comment by rybak** [comment]
When searching "refspec" : https://git-scm.com/search/results?search=refspec
First result : https://git-scm.com/book/en/Chapter-10-Git-Internals-The-Refspec
Link leads to https://git-scm.com/book/en/v2
Should lead to https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

Seems that it is different from #403 but similar to #346 because:
Second link : https://git-scm.com/book/en/Git-Internals-The-Refspec
Leads correctly to : https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

Screenshot 
![git-scm-search](https://cloud.githubusercontent.com/assets/624072/11412546/2ede953e-93ef-11e5-826d-3ff2ca81ad95.png)
