### ISSUE TITLE
Orange text on site difficult to read

### ISSUE THREAD

**Issue by gnetsys** [git/git-scm.com#359]
The tutorial site is difficult to read and strains the eyes because the command colors are orange on a white background.

**Comment by pedrorijo91** [comment]
would this just be considered a very low-priority issue, or it's a "wont' fix" case @peff ?

**Comment by peff** [comment]
I'm happy to entertain PRs that change the color scheme to something with higher contrast, but bear in mind that I have no design taste whatsoever. I'd rely on the community to do review, and probably ping @jasonlong for input.

**Comment by jasonlong** [comment]
The bold orange headings have pretty decent contrast ([AA Large](http://jxnblk.com/colorable/demos/text/?background=%23fcfcfa&foreground=%23ef391a)), but maybe @gnetsys was referring to the command reference styling?

![screen shot 2017-02-07 at 11 23 53 am](https://cloud.githubusercontent.com/assets/6104/22700344/59ac27ca-ed28-11e6-8077-65fd3f4f189c.png)

I agree that this isn't the best. I'd like to get some new visual updates going (@peff I'd like to get involved here again) and I will keep this issue in mind.

**Comment by peff** [comment]
@jasonlong Yeah, I'm not really sure specifically what the complaint is. The issue is quite old (volunteers are triaging stale issues this week), so we'll see if @gnetsys gives more detail.

As far as more visual updates, I'm open to PRs and generally trust your judgement. Do note that there's some discussion happening in #942 regarding moving the content to a static site generator like Jekyll. I don't think that would conflict with any visual re-design, but it may end up with textual conflicts as files are moved around and tweaked.

**Comment by jasonlong** [comment]
I'm starting to close issues that are currently implemented in the `v2` branch. 

[Project board here](https://github.com/git/git-scm.com/projects/2)

**Comment by jasonlong** [comment]
For reference, the new code blocks look like this. 

<img width="712" alt="screen shot 2018-03-05 at 9 58 35 pm" src="https://user-images.githubusercontent.com/6104/37011969-650b8c7e-20c0-11e8-9d7e-dad60dd88090.png">
