### ISSUE TITLE
Provide a PDF, mobi and ePub files for all translated languages

### ISSUE THREAD

**Issue by AlanCristhian** [git/git-scm.com#379]
It would be great to be able to download the book in other languages :D

**Comment by sxlijin** [comment]
Has there been any progress on this since 2014?

**Comment by peff** [comment]
Atlas is out of the picture now, and PDFs can be built directly out of the progit2 repository (or translation repos). In theory, anyway.

I'm not sure what that would look like. If translation projects publish builds on their releases pages, we could link to those. Otherwise we have to build them all ourselves. And that build procedure depends on stuff like #942, and how it shapes up.

So I think this is a reasonable wishlist item, but not something to move on immediately.

**Comment by peff** [comment]
Yeah, this is solved. The individual translation projects build the artifacts themselves and make them available via GitHub's "releases" mechanism (via an automated CI task). And then we poll those nightly to create the links. Thanks @jnavila who did all the work here in bbd4a38e11a1c8614c615a2f8c6e09d11c0b8f95 and elsewhere.
