### ISSUE TITLE
Right to left support in documentation, for RTL languages

### ISSUE THREAD

**Issue by nik-kashi** [git/git-scm.com#449]
Currently documentation in RTL languages (such as Farsi) show as following:

![image](https://cloud.githubusercontent.com/assets/4746836/4434084/8c3ccecc-4700-11e4-9d2e-fcae9237a3c0.png)

while the correct mode is:
![image](https://cloud.githubusercontent.com/assets/4746836/4434086/afd68850-4700-11e4-885d-e10e7dc7989a.png)

it can be done by adding `direction: rtl;` css to container div

**Comment by pedrorijo91** [comment]
@peff I was thinking if this would be a good hacktoberfest candidate, but I've no clue how hard it would be to fix this?

**Comment by peff** [comment]
@pedrorijo91 I'm not sure. I guess we'd have to insert this styling only into the pages for RTL translations of the book content. So it would really involve munging the content as it gets sucked in from the progit repo (in `lib/tasks/book2.rb`).

Partial translations would be tricky, since this would have to be applied partially. But maybe we can just ignore that for the initial attempt.

It may also be tricky for translations which are only done for v1 of the book. I think the import process there is a bit different (though probably it should be able to do something similar).

**Comment by jnavila** [comment]
I guess that would require two things for v2:
 *  add a new field in `all_books` at https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake#L167 with the direction
 * tweak the html generation to insert it in each generated page.

**Comment by dscho** [comment]
Let's just close this, there has not been enough activity to merit keeping this ticket open.
