### ISSUE TITLE
.gitattributes documentation regarding newlines is unclear

### ISSUE THREAD

**Issue by DanielSank** [git/git-scm.com#465]
Refer to this page: http://git-scm.com/docs/gitattributes/2.1.2

The document refers to "normalization" but it never defines the term. At each usage of the term it is not clear whether it is talking about line ending changes which occur when writing to the database or when writing out to the working copy.

Given the large number of of questions on the topic of how to handle newlines in git, I think the documentation on this topic requires significant improvement. I am unable to do this as I do not understand how it works, precisely because the documentation is unclear.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).

This specifically seems to be result from confusion resulting from inconsistent cross-platform newlines, if I'm not mistaken, which IME anyone who's gotten to the point where they're using Git usually knows.

**Comment by peff** [comment]
To clarify @sxlijin's comment, the manpages are pulled directly from Git automatically without modification beyond some formatting markup. So any content-level fix would have to happen there first.
