### ISSUE TITLE
Misleading filter on GUI page

### ISSUE THREAD

**Issue by GadgetSteve** [git/git-scm.com#513]
The filter on OS button on the GUI clients page seems to only filter for exact matches so if I click on it from a Linux box it shows no tools because all the Linux GUI clients also support at least one other OS. The filter should be something like `Linux in OS` rather than `OS == Linux` so as to show all the GUI tools that support Linux, _or whatever_, rather than the tools that support **only** my OS. 

This will be very misleading for users of every OS because some of the best, _IMHO_, tools are cross platform rather than single platform.

**Comment by johnhaley81** [comment]
...Bringing this back from the dead...

Would anybody be open for a PR that would classify tools as:

 - Cross Platform
 - Windows Only
 - Mac Only
 - Linux Only

?

**Comment by peff** [comment]
Hrm. I don't see the original problem here. If I click the "Only show GUIs for my OS (Linux)" button, then I see, for example, SmartGit, git-cola, etc, that are cross-platform.

Can you confirm that the problem still exists?

**Comment by sxlijin** [comment]
Bump - related to #777.

**Comment by peff** [comment]
AFAICT, this problem is fixed (the filter code will pick out the individual platforms that match what you're filtering for).

It's semi-related to #777, but that one is specifically about having more options to click, not what clicking each option does.

I do think an option for "show only cross-platform" (or better still, allow arbitrary combinations like "show mac _and_ linux") might be useful. That's outside the scope of this original issue, though (and hopefully rather than opening a new issue for that, somebody would open a PR :wink:).
