### ISSUE TITLE
Old company/project logos

### ISSUE THREAD

**Issue by valerie-makes** [git/git-scm.com#595]
Over a third of the company/project logos on the homepage are old versions which should be updated:
- Google
- Facebook
- Twitter
- Netflix
- Android
- Eclipse

**Comment by anowlcalledjosh** [comment]
More logos are outdated now, including:

- Microsoft
- Ruby on Rails (possibly? not sure what the logo actually is)
- Qt

--

IANAL, and the following may be irrelevant due to fair use or similar.

The GNOME logo doesn't appear to have a ™ or ® symbol attached to it, which [according to the GNOME Foundation](https://www.gnome.org/logo-and-trademarks/) it should.

Infodump:

- [Google][google] wants everyone to ask permission to use their logo, and also says:

  > We generally do not approve the use of our logo in third-party marketing materials.
- [Facebook][facebook] doesn't have the wordmark available and disallow modification.
- [Twitter][twitter] doesn't have the wordmark available and disallow modification.
- [Netflix][netflix] won't even let you read their guidelines without signing up for a 'partner account'.
- [Android][android] doesn't have the wordmark available, but allows modification (the Android robot is under CC BY 3.0)
- [Eclipse][eclipse] has an [enormous document](https://eclipse.org/legal/logo_guidelines.php) detailing how their logo may be used.

| Logo | Permission required? | Wordmark available? | Modifiable? |
|------|----------------------|-----------|-------------|
| Google | Yes | Presumably | No |
| Facebook | No | No | No |
| Twitter | No | No | No |
| Netflix | Yes? | ? | ? |
| Android | No | No | Yes |
| Eclipse | No | Yes | [No](https://eclipse.org/legal/logo_guidelines.php#ProperEclipse) |
| Microsoft | No | Yes | No |
| Rails | No | Yes | ? |
| Qt | ? | Yes | ? |

Again, IANAL; all of this may be unnecessary.

[google]: https://www.google.co.uk/permissions/using-the-logo.html
[facebook]: https://www.facebookbrand.com/
[twitter]: https://about.twitter.com/press/twitter-brand-policy
[netflix]: https://partner.netflix.com/en_us/terms/
[android]: https://developer.android.com/distribute/tools/promote/brand.html
[eclipse]: https://eclipse.org/artwork/

**Comment by peff** [comment]
IANAL either, though in general we should seek to do whatever each logo-holder wants, whether we're legally required to or not. And in general, I think it makes sense to err on the side of caution.

But most of these logos have been here for years, and I don't know what permissions may have been secured in the first place. The git history isn't all that helpful; @schacon @jasonlong, a lot of these came from b4fc467b9de749ad0d3ab2397b243ac32db9a2d7. Do you happen to remember how the list of logos was compiled?

As far as some of them being outdated, pull requests are welcome.

**Comment by jasonlong** [comment]
Sorry for the delay, I was on vacation last week.

Yeah, I don't really remember the details on how those logos were compiled. I feel like @schacon coordinated that side of it and I added them as they were green-lit. Hopefully he can chime in here.

**Comment by C-Lion** [comment]
I'd like to work on this issue as my mini-project for GCoC. From reading it, I see that besides finding the logos, I will need to so some research & possibly attempt to contact some logo owners (or work with someone from the git team to coordinate that), so I realize this is not going to be done over a weekend, or even a month potentially. Based on GSoC the mini-project document, this  is ok, but you also asked me to contact you for an official ok before jumping in.

**Comment by sxlijin** [comment]
@peff

**Comment by tgummerer** [comment]
@C-Lion I guess you are talking about micro-projects documented in https://git.github.io/SoC-2017-Microprojects/?  For that you should really look for a project working on the git source, not on the git-scm.com website.  One of the main purposes is to get familiar with the git source code and the patch submission process, which is quite different from contributing to this repository.

**Comment by C-Lion** [comment]
Thanks for the quick response. Based on this quote it seemed that the process was more important than the actual work done. 

> the coding aspect of the change can be almost trivial, but to make the change the student has to become familiar with many of the practical aspects of working on the Git project.

I have looked though the main repository and the mailing lists several times and don't see anything that fits this description that is not already being worked on.  Since web development is one of my stronger skill sets this seemed like a better choice as I originally assumed the micro-project had to be complete by 3 April. I understand now that the micro-project does not have to be done by that day, only started?

 If this is the case, perhaps you can suggest something closer to my skill that will also help me learn more about working on the main repository? 

I have basic C & bash skills as well & have been using git locally & on github for about a year. I know what some of these commands do but am at a loss as to which one might be "trivial" as well as how to learn how to fix one. 

Also, I assume that repo a better place to be asking about those things but until I know which one to work on is there a general communication tool I should be using to have this sort of meta issue discussion? Thanks in advance for you time.

**Comment by sxlijin** [comment]
The mailing list at git@vger.kernel.org is the best place for this to be perfectly honest, even if you're just trying to determine if there's any web development work that you could contribute to the Git project.

**Comment by jasonlong** [comment]
FWIW I'd like to start doing some cleanup to the site soon. It's been 5 years since I designed it and it's starting to feel a little dated. At the least, I'd like to at least improve the CSS and markup (something I started a couple years ago and stalled out when my PRs didn't get merged - see https://github.com/git/git-scm.com/pull/526)). And if possible, I'd like to do a visual refresh of the overall look and feel.

**Comment by peff** [comment]
I am more than happy to have somebody helping with this issue, but I agree it's not a great micro-project. I don't think working on the website is an option for a GSoC project (I think Google's rules are that it should be code, not documentation or a website; and while the site _is_ technically a Rails app with code, I don't think that's where most of the work is). So any project would probably be on the git.git repository itself.

And since the point of the micro-project is to get an intro to the submission process for that repository (both for the student, and for contributors there to interact with the student), a project here doesn't really help that. So my gut reaction is that no, this probably isn't suitable for a micro-project (it's also not very micro; that's not a showstopper by itself, but it's probably more important for students to focus on project proposals than on biting off a big micro-project).

**Comment by peff** [comment]
@jasonlong Cleanup is welcome. I don't think there are any major visual changes in the pipeline, so it's a good time if you want to touch things broadly across the site. And I agree there are a few bits that could use some refreshing. I think the content could use a once-over, too (e.g., SVN performance comparison numbers from 2009 aren't as interesting anymore). But that's not really your responsibility. :wink:

**Comment by jasonlong** [comment]
As part of the WIP design updates, I was thinking of proposing dropping company logos from the homepage. I think we're beyond needing to convince people to use Git by name dropping.

**Comment by pedrorijo91** [comment]
I won't oppose removing the logos. I have a vague idea that the problem was arised before and some was against it, but I can't find the issue/pr where that was discussed

**Comment by prasadgujar** [comment]
hello everyone
@davidbailey00 @anowlcalledjosh @peff @C-Lion @jasonlong is anyone `working`on this issue?
if not let me know I m interested `in working with this issue?

**Comment by jasonlong** [comment]
@prasadgujar They will go away in the redesign, but I don't believe there are any current efforts to update the current design.
