### ISSUE TITLE
"Reset Demystified" has no author

### ISSUE THREAD

**Issue by steveklabnik** [git/git-scm.com#597]
http://git-scm.com/blog/2011/07/11/reset.html

![2015-09-28-112828_319x72_scrot](https://cloud.githubusercontent.com/assets/27786/10140110/07646c02-65d4-11e5-8709-a2036ed2c1b5.png)

I would guess that the author is @schacon , from the examples, and "I" when talking about Pro Git, but I can't be sure.

**Comment by pedrorijo91** [comment]
it seems that we no longe display the "by" label if no author. should the issue be closed, or should we try to find the author and add it @peff ?

**Comment by steveklabnik** [comment]
I guess this is "WONTFIX" then?

**Comment by peff** [comment]
@steveklabnik Sorry, I thought the bug was "there's an ugly by label without a name". That bug is fixed already.

If the bug is "I have no idea who wrote the blog post", that's probably best answered [by git-blame](https://github.com/git/git-scm.com/blame/master/app/views/blog/posts/2011-07-11-reset.html). I certainly don't mind adding @schacon's name to the published page, but I assumed from the blank `author` field that he didn't want authors listed on the blog posts.

**Comment by steveklabnik** [comment]
Great! I'm happy with whatever, personally. 👍
