### ISSUE TITLE
Windows Install Path with Spaces breaks scripts/exes (update-ca-trust)

### ISSUE THREAD

**Issue by erichiller** [git/git-scm.com#610]
I encountered this with `update-ca-trust` so far. When I run I get

```
p11-kit: 'Files/cmder/vendor/git-for-windows/mingw32/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/cmder/vendor/git-for-windows/mingw32/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/cmder/vendor/git-for-windows/mingw32/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/cmder/vendor/git-for-windows/mingw32/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/cmder/vendor/git-for-windows/mingw32/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
```

Which is obviously due to the fact that I have git installed in 
`C:/Program Files/cmder/vendor/git-for-windows/`

But the script references from base git-for-windows and therefor I don't really have a way to "just add quotes" Is this a bug or am I missing something?

(Windows 10) & git version 2.5.2.windows.2

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).
