### ISSUE TITLE
Are merged PRs actually being deployed?

### ISSUE THREAD

**Issue by swisspol** [git/git-scm.com#629]
I'm thinking of #577 I sent and was merged 3 months ago but is still not visible. There are others affected too.

**Comment by peff** [comment]
@swisspol I don't know what the old plan was, but it does seem like PRs sometimes languished (and we are definitely not auto-deploying master to Heroku). I have push access to the Heroku site now, so I'm going to make sure anything I merge is deployed, going forward.

I'm going to close this, as your PR should be out now (I've deployed several times since December), but please reopen if it isn't.
