### ISSUE TITLE
Adding my compny

### ISSUE THREAD

**Issue by osama9** [git/git-scm.com#646]
We have installed git server locally, is this the only requirement to add my company to git-scm.com home page?

**Comment by randomecho** [comment]
Companies listed under the "Companies & Projects Using Git" section of the homepage typically represent large, well-known businesses and organisations. That would be the bigger factor on whether or not your company would be listed.

**Comment by Download** [comment]
Too bad to hear that. There should be no discrimination against small companies in an Open Source project.

**Comment by pedrorijo91** [comment]
@peff assuming there's no plan to add a section to include all companies using git, this should be closed?

**Comment by peff** [comment]
The point of the "companies using Git" section is bragging rights for Git. If there's a company or other entity using Git that's _notable_ (i.e., would encourage other people to use Git because they are), then we should consider adding it (but only after getting an OK from that company).

But we can't just include everybody who uses Git in that section.  There's way too many to list these days.
