### ISSUE TITLE
Git Bash no longer works in Console2

### ISSUE THREAD

**Issue by denno020** [git/git-scm.com#653]
I have been using Console2 as my Git terminal, loading in a Git bash window, however I made the mistake of installing Docker, which uninstalled the version of Git that I had, and installed the latest version. Now when I set up my Console2 configuration to load in the Git bash window, opening Console2 will trigger Git bash to open it's own window, outside of Console2..

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).
