### ISSUE TITLE
git-gui is not available on git version 2.5.4 (Apple Git-61)

### ISSUE THREAD

**Issue by clemens-tolboom** [git/git-scm.com#678]
On https://git-scm.com/downloads/guis report

> Git comes with built-in GUI tools for committing (git-gui) and browsing (gitk), but there are several third-party tools for users looking for platform-specific experience.

which is unfortunately not true for my git version. Should we fix that?

**Comment by pedrorijo91** [comment]
what is your git version @clemens-tolboom ?

which OS are you running?

how did you install git?

**Comment by clemens-tolboom** [comment]
The title says _git version 2.5.4 (Apple Git-61)_ ;-)

**Comment by clemens-tolboom** [comment]
Now I have _git version 2.10.1 (Apple Git-78)_

**Comment by peff** [comment]
Hmph. I don't want to mislead users with our text. At the same time, `git-gui` _does_ ship with the git source code. But you are using a binary packaging of git made by a third party (Apple) who chooses not to include the command.

I have no idea if there is a way to get `git gui` from Apple at all, or if the right answer is "install from source or from homebrew". But unlike the other GUI options, it is not really distributed separately as a third-party program.

**Comment by clemens-tolboom** [comment]
@peff thanks for the information.

Installing through `brew install git` and starting a new terminal gives `git gui`

Guess we can close this apart maybe a mention regarding Apples build in version?

**Comment by peff** [comment]
I started to add a comment to the page to that effect, but I think it snowballs quickly. Because binary packagers might not include the tools at all (which AFAIK is the case for Apple), or they might be in a separate package (e.g., `apt-get install git-gui` on Debian). Everything I wrote seemed to raise more questions than it answered.

I'm going to close this for now as not-a-bug, but if somebody wants to open a PR improving the instructions around alternate packages, feel free.
