### ISSUE TITLE
git merge-base documentation error

### ISSUE THREAD

**Issue by Wopple** [git/git-scm.com#680]
In the git-scm v2.5.1 docs for merge-base, I see this graph:
```
     o---o---o---B
    /
---o---1---o---o---o---A
```
but from `git help merge-base` v2.3.3 I see:
```
         o---o---o---B
        /
---o---1---o---o---o---A
```
The different versions could have different implementations for merge-base, but that seems unlikely.

**Comment by williammorgan** [comment]
I have also noticed and been nearly misled by this.  The error can be confirmed by looking at the following two links.
A mirror of the man page for 2.8.2:
https://github.com/git/git/blob/v2.8.2/Documentation/git-merge-base.txt
The git-scm page for 2.8.2:
https://git-scm.com/docs/git-merge-base/2.8.2

The error is related to the use of both tabs and spaces in the original diagram.  Perhaps the git version of the diagram should use only spaces or perhaps git-scm.com should translate the tab characters into the number of spaces expected by the diagram author.

**Comment by peff** [comment]
Upstream git documentation assumes an 8-space tabstop. It looks like asciidoctor uses 4 by default. There was some work in https://github.com/asciidoctor/asciidoctor/issues/1170 to allow setting the tab size per document. So I think it would require one of:

  1. Upstream git stops using tabs in diagrams (which is not an unreasonable thing to do anyway, just because it makes it more robust to exactly this kind of issue).

  2. Upstream git starts setting a tabsize attribute on the document.

  3. When git-scm.com pulls in the documentation, munging them to specify a tabsize attribute somehow.
