### ISSUE TITLE
Error when using single quotes instead of double quotes in $ git commit

### ISSUE THREAD

**Issue by julmot** [git/git-scm.com#690]
Running the following command on a Windows 7 computer like described in the [book](http://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository):

``` bash
$ git commit -m 'initial project version'
```

will cause the following error:

![err](https://cloud.githubusercontent.com/assets/8310677/13253783/32882390-da3e-11e5-8c2c-9ae4a1253e94.png)

It works when using double quotes:

![double](https://cloud.githubusercontent.com/assets/8310677/13253794/3ecf79d2-da3e-11e5-862c-a7dc1817a9dd.png)

This is known on [StackOverflow](http://stackoverflow.com/questions/16951207/git-commit-error-pathspec-commit-did-not-match-any-files-known-to-git). 
I would have liked to change this myself quickly, but I am unable to find the related content file in this repo.

**Comment by julmot** [comment]
@schacon

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this seems to be specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).

Also, I can't reproduce this issue.
