### ISSUE TITLE
File version is not updated beyond 2.7.0.0

### ISSUE THREAD

**Issue by wrycu** [git/git-scm.com#711]
Although the "product version" was incremented to 2.7.3, the file version was left at 2.7.0.0.  Many automation tools (e.g. patchers) use the file version to determine if an update has been applied or not.  Would it be possible to increment the file version (potentially on the next release)?

![image](https://cloud.githubusercontent.com/assets/4709746/13855682/02826a54-ec48-11e5-83cf-51ca14eae98f.png)

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).
