### ISSUE TITLE
fatal: unable to get current working directory: No such file or directory

### ISSUE THREAD

**Issue by Silberling** [git/git-scm.com#721]
Two computers, both Win10 64bit using a Linux based NAS (SMB with RW access on that share). On one its working fine. On the other one I get this

> Cloning into 'local'...
> fatal: unable to get current working directory: No such file or directory
> fatal: The remote end hung up upon initial contact

when I do

`git clone file://z:/Git/origin local`
and

> fatal: unable to get current working directory: No such file or directory

when I do

`git init --bare x`
I found several similar issues without any solution like this: [https://www.bountysource.com/issues/26949309-pushing-to-unc-paths-seems-broken-but-mounted-network-drives-works](https://www.bountysource.com/issues/26949309-pushing-to-unc-paths-seems-broken-but-mounted-network-drives-works)

Is there any way to make git more verbose to find out where the problem is? How do I solve this problem? I don't know where to start.

As this problem is for some time now I'd like to point out I've tried Git-Bash on Windows 10 64bit using 2.7.4 today.

```
user@HOST MINGW64 /z/Git
$ git init --bare RepoTest
fatal: unable to get current working directory: No such file or directory
```

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).
