### ISSUE TITLE
Code blocks rendering html entities

### ISSUE THREAD

**Issue by styfle** [git/git-scm.com#753]
Compare these two pages: 
* [/en/v2/Git-and-Other-Systems-Migrating-to-Git](https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git#TFS) 
* [/it/v2/Git-and-Other-Systems-Migrating-to-Git](https://git-scm.com/book/it/v2/Git-and-Other-Systems-Migrating-to-Git#TFS)

The `en` page is showing code blocks incorrectly, for example:

    PS&gt; tf history $/myproject -recursive &gt; AUTHORS_TMP

The `it` page is showing the code blocks as expected, for example:

    PS> tf history $/myproject -recursive > AUTHORS_TMP

**Comment by peff** [comment]
Interesting. Doubly so because that chapter doesn't actually seem to be translated in the Italian version, meaning that it is ultimately coming from the same source in progit/progit2.

It looks like git-scm.com ultimately gets its Pro Git content by downloading a pre-built [HTML ebook](https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.zip). Pulling that down manually, it looks like the damage is already done there; it has `<code>` tags referring to `&amp gt;`. So the breakage is somewhere in the progit build toolchain, but I don't know how that works. /cc @schacon and @ben 

It is weird that the English version is broken but the Italian one isn't. Looking at the db records, it seems that our URL for the Italian version is from 2015-08-10, whereas the English one is from 2016-03-22. So maybe something simply changed in the progit toolchain between those times, and if the Italian one were rebuilt today, it would be similarly broken.

**Comment by YueLinHo** [comment]
My guessing:
Once each language repository of progit2 has a new commit pushed, it will trig Atlas to auto build somethings, including HTML book. (see [progit2 issue 585](https://github.com/progit/progit2/issues/585))

**Comment by peff** [comment]
@YueLinHo pointed out that this is indeed a bug in upstream progit, and is being tracked in https://github.com/progit/progit2/issues/371. I'm going to keep this open as tracking for the issue, even though there's really not a good fix on the git-scm.com side.

**Comment by peff** [comment]
More discussion in #645, and a possible workaround in #740.

**Comment by jnavila** [comment]
We could patch this when importing the book from atlas into the db. I'll look into the rake script.

**Comment by styfle** [comment]
Looks good! Thanks :100:
