### ISSUE TITLE
About Figure 3-9. Divergent history

### ISSUE THREAD

**Issue by abdullaheid** [git/git-scm.com#771]
I'm just wondering if the master and the testing branches pointers in the figure 3-9 were pointing correctly to the right commits or not?. Based on the previous figure 3-8 in the same page, I think the master branch should point to 'c2b9e' not to '87ab2'.

https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

Yours,

**Comment by peff** [comment]
Yes, I think you are right.

The git-scm.com site just reformats the generated ebook; the content actually resides in the progit repository. Looks like this was discussed in https://github.com/progit/progit2/issues/313, which claims it's fixed there. But we've certainly re-imported the book since then. I wonder if it's still broken in the generated ebook (which is where we pull the content from), or if for some reason we're not updating the images when we pull in new versions of the ebook.

**Comment by peff** [comment]
I just checked the latest build of the [HTML ebook](https://progit2.s3.amazonaws.com/en/2016-03-22-f3531/progit-en.1084.zip) and indeed, it has the fixed image. So something about the `genbook2` tasks is not pulling in the updated image.

**Comment by peff** [comment]
> So something about the genbook2 tasks is not pulling in the updated image.

Indeed. That "something" seems to be that the book-update task does not pull updated images at all! It looks like the initial ones were manually copied into the repository in 2014 when the the v2 edition was published, and they have to be manually updated. I just opened https://github.com/git/git-scm.com/pull/775 to pull in the new versions.
