### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by bappi** [git/git-scm.com#808]
https://git-scm.com/download/mac This page doesn't start the download right away

**Comment by Sicaine** [comment]
The error might be the same i get:

"Mixed Content: The page at 'https://git-scm.com/download/mac' was loaded over HTTPS, but requested an insecure resource 'http://sourceforge.net/projects/git-osx-installer/files/git-2.10.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect'. This request has been blocked; the content must be served over HTTPS."

The only place i found (https://github.com/git/git-scm.com/search?utf8=%E2%9C%93&q=sourceforge.net%2Fprojects%2Fgit-osx-installer%2Ffiles%2F&type=Code), where the https is missing is spec/data/downloads.rss but i don't understand how this correlates to the page.

**Comment by jvusich** [comment]
@Sicaine is correct in that the download link seems to be insecure HTTP and not HTTPS in the current build of the site. I can't reproduce this locally (`rake downloads` produces an HTTPS link).

However, even with the correct HTTPS link, the automatic download does not start. This seems to be SourceForge-related. The download link loads (verified via Chrome's Network console) but it's merely [an HTML page](https://sourceforge.net/projects/git-osx-installer/files/git-2.10.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect) with another client-side redirect to the actual download.

When the same URL is fed into `wget`, it results in a series of 301/302 redirects, resulting in successful download of the `.dmg` It seems that SourceForge is doing some heuristic on the request to tell if it's coming from a browser or not. I'm not sure this issue is easily addressable.

**Comment by pedrorijo91** [comment]
Still happens, but my console shows (didn't try to dig anymore):

```
Failed to load resource: the server responded with a status of 404 ()
session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9 Uncaught TypeError: Cannot set property 'version' of null
    at Object.package_obj (session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9)
    at c.source.google.a.gloader_ready (session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9)
    at jsapi?callback=gloader_ready:45
mac:1 Refused to display 'https://sourceforge.net/projects/git-osx-installer/files/git-2.14.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
sourceforge.net/projects/git-osx-installer/files/git-2.14.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE
```

**Comment by amitmalani** [comment]
is this still an ongoing issue?
requests are getting timed out.

**Comment by pedrorijo91** [comment]
yes, this problem has not been solved yet. If you want to help by contributing with a PR you are welcome @amitmalani  :)

**Comment by sxlijin** [comment]
FWIW going off @pedrorijo91's console logs, this seems like a somewhat complicated fix. There are two parts: part one is that because SourceForge now enforces https (hurrah!) and also sets x-frame-options to sameorigin, using an [iframe](https://github.com/git/git-scm.com/blob/ad939da48ea50efccaeef956916339ad10f41df2/app/views/downloads/downloading.html.erb#L23) to trigger the download is no longer a viable auto-download solution, which presumably means that JS should be used to trigger a download (the solution that comes to mind is using JS to initiate a click event after `onDocumentReady` fires), but this requires having a download link.

This is part two - extracting the download link seems to require some amount of trickery, because what we currently do is actually render the SourceForge auto-download page in an iframe on our auto-download page, i.e. we've been delegating the work to SourceForge. In theory, this is totally doable, but to the extent that I've looked into this I have no idea how to extract that link.

**Comment by amitmalani** [comment]
@pedrorijo91 dont think I am equipped to fix that :) How else could I be of any help?

**Comment by dscho** [comment]
Is this still a problem, or can this ticket be closed?
