### ISSUE TITLE
Git version 2.9.2.windows.1 performance issue

### ISSUE THREAD

**Issue by Rixuel** [git/git-scm.com#811]
I'm using Git version 2.9.2 for Windows.

I don't know if it's just me, but there is a performance or optimization issue of the Git Bash.

Here the steps:
1) Open Git Bash
2) When Git Bash is open, hold "Enter"
3) There are some delays.

In a Command Prompt or in the very old version of Git Bash, there is no delay.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you should follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).
