### ISSUE TITLE
Use GNU Short Option Style "clumping" rules not obeyed for `git stash`

### ISSUE THREAD

**Issue by Nowaker** [git/git-scm.com#829]
```
% git stash -ku                                             
error: unknown option for 'stash save': -ku
(...)
% git stash -k -u
Saved working directory and index state WIP on master: (...)
(...)
```

In other parts of git, clumping (as defined by [GNU Short Option Style guide](https://www.gnu.org/software/tar/manual/html_node/Short-Options.html#SEC37)) works, for example:

-v for verbose, -m for message:
```
% git commit -vm 'xd'
[master a560195] xd
 1 file changed, 91 insertions(+), 51 deletions(-)
 rewrite spec/actions/hosting/meta_machine/upgrade_plan_spec.rb (96%)
```
-q for quiet, -m for message
```
% git commit -qm 'xd' 
(no output)
```

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website, not git itself. Bug reports should generally go to the [mailing list](https://git-scm.com/community).

That being said, the reason for the inconsistency is that each git sub-program is responsible for its own option parsing. There is a `parse_options` library that does the proper clumping (and handles `--long=foo` versus `--long foo`, for instance); things have been slowly migrating to it over the years but there are a few spots which haven't yet. In C, the notable one is the revision/diffopt parsing. In shell, scripts should be able to feed their options to `git rev-parse --parseopt`, but it looks like `git-stash` does not do so (probably because it needs to do parsing in several stages, depending on the command name it gets).

Patches to convert it to use `rev-parse --parseopt` would be welcome.
