### ISSUE TITLE
Git submodule page - foreach section - quoting problem in command example

### ISSUE THREAD

**Issue by gotjoshua** [git/git-scm.com#855]
https://git-scm.com/docs/git-submodule
in the foreach section there seems to be a typo (tick/quote problem):

> As an example, git submodule foreach 'echo $path `git rev-parse HEAD’ will ...

I changed the command to this so that it works:

```
git submodule foreach 'echo $path `git rev-parse HEAD`'
```

cheers

**Comment by pedrorijo91** [comment]
the documentation is generated from the git man pages right @peff ?

**Comment by jnavila** [comment]
I think the man pages are correct, but asciidoctor interprets the closing \`\' characters as oriented quotes.

See http://asciidoctor.org/docs/migration/#migration-cheatsheet

@peff, this is typically a place where #928 would be useful, wouldn't it?

**Comment by peff** [comment]
Sadly, #928 does not seem to fix it (at least in my quick testing).

I think the source is bogus, though. We are in a `+` monospaced block and want to literally show the single-quotes. The first one is backslash-escaped, but the second is not. And #928 does not apply because the source uses the `{backtick}` inline subsitution instead of an actual backtick.

I've sent a [fix upstream](http://public-inbox.org/git/20170213210549.jns7asrvjp3lb5wc@sigill.intra.peff.net/).

**Comment by Cinderhaze** [comment]
I just saw the same bug in our cloned version of the docs, glad to see an issue was already raised and addressed!

**Comment by jnavila** [comment]
Closing as this is fixed upstream.
