### ISSUE TITLE
Problem in german version of chapter 4.4 Git on the Server - Setting Up the Server

### ISSUE THREAD

**Issue by unlimited101** [git/git-scm.com#858]
This insturction doesn't work:

https://git-scm.com/book/de/v1/Git-auf-dem-Server-Einrichten-des-Servers

There are missing several steps which are described in the english version:

https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

E.g. the chmod commands are missing in the german version

**Comment by jnavila** [comment]
This is due to the second edition of Progit not being translated to German. However, this project is dedicated to the git-scm.com website. Your issue deals with the progit book whose project is located at 
https://github.com/progit/progit2

There is already a team of German translators who would be glad to receive some help.

**Comment by Sicaine** [comment]
@peff this issue can probably just be closed right?
