### ISSUE TITLE
Git Basics > Tagging

### ISSUE THREAD

**Issue by lukasradek** [git/git-scm.com#861]
Hello,
it is not obvious from the tagging blogpost, when you actually should run the tag command. It is obvious while tagging some old commit, but not when I want to tag the curent one.
Have a good one,
Luky

//edit: tontag -> to tag

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

**Comment by peff** [comment]
I think this actually has to do with one of the blog posts on the site. I didn't dig further, though.

**Comment by sxlijin** [comment]
@lukasradek is this still an issue for you, and if so, could you clarify? Otherwise I'd move to close this issue.

**Comment by lukasradek** [comment]
@sxlijin hello Samuel :-), peff was actually right.

To be honest (after readeing through the whole Git guide + working with git for a while), my intuition would probably found out now, but since it is a tutorial, it should be explicit I guess :-).

In the "creating tag" paragraph, it really is not exactly clear when you should run the tag cmd, or rather what happens then. (As I said above... now with some experience) I would guess, it tags the last made commit. But as well as that it might create a new commit a then tag it. 

The difference I see here is that when you run the tag command, you are not tagging what is actually in your working directory, but rather the state, that was commited last. (sometimes, that can be the same thing... sure).

I would add something like this into the tutorial:
"The tag commad tags the last commit, you have made or the one you specify as an option"

Have a nice day :-)

**Comment by sxlijin** [comment]
Ah, that isn't a blog post. That's actually the Pro Git book, so you actually want to raise it over at the [progit/progit2](https://github.com/progit/progit2) project.

And to be honest, I'm not quite sure how to improve it in the way you suggest. That section already mentions specifically:

> Like most VCSs, Git has the ability to tag specific points in history as being important. Typically people use this functionality to mark release points (v1.0, and so on). In this section, you’ll learn how to list the available tags, how to create new tags, and what the different types of tags are.

and later: 

> A lightweight tag is very much like a branch that doesn’t change – it’s just a pointer to a specific commit.

so I'm not too sure how someone might think a tag can refer to the current working directory, which is never itself associated with a commit. That being said, it's been a long time since I learned tags, so there very well might be a content improvement worth making there.

**Comment by lukasradek** [comment]
Sure :-), not a blog post, wrong word chosen.

My point was...
when I create tag like:
`git tag -a v1.2 9fceb02`
it is pretty obvious, it will tag the 9fceb02 commit.

If I create tag like:
`git tag -a v1.2`
I am really not sure, what will be tagged. Last commit? Or will it create a new commit (from current WD) and tag this one? Who knows, the book doesn't say.

I am pretty sure, it makes perfect sense to you, what will be tagged, but when I was learning Git, it wasn't :-). Because the book does not specify it explicitly.

**Comment by peff** [comment]
@lukasradek I'm going to close this issue. That's not a judgement on whether your issue is worthwhile to pursue, but only that if it is going to be pursued this isn't the right venue. It would need to be via the [progit2](https://github.com/progit/progit2) repository, or in Git's manpages (see https://git-scm.com/community).
