### ISSUE TITLE
Syntax Error in git-core/git-filter-branch

### ISSUE THREAD

**Issue by gilgameshskytrooper** [git/git-scm.com#880]
Syntax error near unexpected token `newline'
    /usr/local/Cellar/git/2.10.2/libexec/git-core/git-filter-branch: eval: line 371: `git rm -r --cached --
    ignore-unmatch <file/dir>'

When I enter the command 
    git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch <file/dir>' HEAD

Set Up:
macOS 10.12.1. Git installed via Homebrew, git --version 2.10.2

**Comment by peff** [comment]
The argument to `--index-filter` is run as shell code via `eval`; so the syntax error is in your snippet. The problem is the `<>`, which should not be part of the literal command.

Also, this issue tracker is just for the git-scm.com website. You'll get better answers by asking in one of the venues at https://git-scm.com/community (this one just happened to be easy to answer).

**Comment by gilgameshskytrooper** [comment]
thx
