### ISSUE TITLE
git-bash on windows should warn about missing administrator privileges when trying to create a symlink

### ISSUE THREAD

**Issue by elasti-eitamd** [git/git-scm.com#894]
My remote repo contains a symlink created on linux and pushed into the repo.
I am using windows, and for a not-important reason I deleted the local copy of the symlink which was previously created in my local working repo when I cloned the remote repo.

"git status" - complained that the symlink is deleted - I tried :

git checkout .
git reset --hard HEAD
git checkout -- <symlink path>

Nothing changed, and git-bash finished performing each of the 3 commands above with no errors.

Through trial and error and 2 hours wasted, I found out I need to "right click git-bash, run as administrator", and then everything worked as expected.

If windows CMD can alert the user, why git-bash can't?

**C:\Users\user>mklink sdfsd sdfds
You do not have sufficient privilege to perform this operation.**

**Comment by sxlijin** [comment]
If you're on Windows, then symlinks immediately become *much* more complicated to handle, because NTFS handles links in a fundamentally different manner. The `core.symlink` config exists for exactly this purpose.

Moreover, this is *not* an issue about the git-scm.com website; please see the git-for-windows/git repository for issues re G4W.

@peff this should be closed.
