### ISSUE TITLE
git bash crash on fresh git install

### ISSUE THREAD

**Issue by Magneticmagnum** [git/git-scm.com#943]
When launching git with right-click menu "Git Bash Here", the git bash (minTTY) doesn't launch.  Instead, a mintty.exe.stackdump file gets created with the following:

Exception: STATUS_ACCESS_VIOLATION at rip=001800BE66B
rax=000006FFFC9F9EF8 rbx=00000000000C9EE8 rcx=1FFFFFFFFFFD0000
rdx=FFFFFFFFFFE80000 rsi=000006FFFC6F9EF0 rdi=000006FFFC879EF0
r8 =0000000000180000 r9 =0000000000000000 r10=0000000100000000
r11=000000010040F5C4 r12=000000000000869F r13=000000000000869F
r14=0000000000010000 r15=0000000000000000
rbp=FFFFFFFFFFFF0000 rsp=00000000FFFFC568
program=C:\Program Files\Git\usr\bin\mintty.exe, pid 10176, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

I have tried reinstall  32-bit and 64-bit windows.  

There have been several users who had the same issues online, but their resolutions didn't solve my issue.

Windows 7, Git 2.11.1 package.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this is specifically relevant to G4W, you might also want to follow up over at [git-for-windows/git](https://github.com/git-for-windows/git/issues).

@peff this should be closed.

**Comment by Magneticmagnum** [comment]
Alrighty, thanks!
